# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
np.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [25]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.13923192, 0.39195171, 0.708663  , 0.30333663, 0.05853524],
        [0.21151347, 0.38737848, 0.79787615, 0.59425713, 0.12443283],
        [0.25527419, 0.22522275, 0.54991928, 0.37036699, 0.2521726 ]],

       [[0.30461383, 0.32634731, 0.66451064, 0.51532814, 0.50655957],
        [0.1364767 , 0.29140776, 0.14960988, 0.45504851, 0.31233887],
        [0.8508847 , 0.85355124, 0.59376459, 0.47787742, 0.20022911]]])

In [26]:
# Method 2
a = np.random.rand(2,3,5) 
a

array([[[0.34840628, 0.81763698, 0.94811504, 0.74656074, 0.75241722],
        [0.94472654, 0.51622887, 0.07530949, 0.61288177, 0.31869889],
        [0.08169069, 0.39454525, 0.76634805, 0.98735922, 0.4769996 ]],

       [[0.25296437, 0.94163071, 0.18592862, 0.41593081, 0.98465014],
        [0.15206082, 0.47279906, 0.35575831, 0.23270853, 0.17840039],
        [0.75880799, 0.55773794, 0.50251653, 0.22926288, 0.5870636 ]]])

In [27]:
# Method 3
a = np.random.randint(2,size = (2,3,5))
a

array([[[1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 1, 1, 0]],

       [[0, 1, 0, 0, 0],
        [1, 0, 1, 1, 0],
        [1, 1, 0, 1, 1]]])

#### 4. Print *a*.


In [28]:
# your code here
a

array([[[1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 1, 1, 0]],

       [[0, 1, 0, 0, 0],
        [1, 0, 1, 1, 0],
        [1, 1, 0, 1, 1]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [29]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [30]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [34]:
# your code here
print(a.size)
print(b.size)

30
30


In [35]:
(a.size == b.size)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [38]:
# your answer here
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [39]:
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


In [40]:
(a.shape == b.shape)

False

It does not works coz the size is the same but the shapes differ.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [54]:
# your code here
print(b.shape)
c = np.transpose(b,[1,2,0])
print(c)
print(c.shape)
print(a.shape)

(5, 2, 3)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [55]:
# your code/answer here
d = np.add(a, c)

Coz now the sizes and shapes match.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [56]:
# your code/answer here
print(a)
print(d)

[[[1 0 0 0 0]
  [0 1 1 1 1]
  [1 0 1 1 0]]

 [[0 1 0 0 0]
  [1 0 1 1 0]
  [1 1 0 1 1]]]
[[[2. 1. 1. 1. 1.]
  [1. 2. 2. 2. 2.]
  [2. 1. 2. 2. 1.]]

 [[1. 2. 1. 1. 1.]
  [2. 1. 2. 2. 1.]
  [2. 2. 1. 2. 2.]]]


d = a + 1 for each element as c is the transposed of b, which was made of ones.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [60]:
# your code here
e = np.multiply(a,c)
print(e)

[[[1. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1.]
  [1. 0. 1. 1. 0.]]

 [[0. 1. 0. 0. 0.]
  [1. 0. 1. 1. 0.]
  [1. 1. 0. 1. 1.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [61]:
# your code/answer here
print (a)

[[[1 0 0 0 0]
  [0 1 1 1 1]
  [1 0 1 1 0]]

 [[0 1 0 0 0]
  [1 0 1 1 0]
  [1 1 0 1 1]]]


x*1 = x. So if a is multiplied by c, which is made of ones, then e = a*c = a, meaning a = e.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [62]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("d_max is",d_max)
print("d_min is",d_min)
print("d_mean is",d_mean)

d_max is 2.0
d_min is 1.0
d_mean is 1.5333333333333334


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [64]:
# your code here
f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [70]:
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range (len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 25
            elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = 75
            elif d[x][y][z] == d_mean:
                d[x][y][z] = 50
            elif d[x][y][z] == d_min:
                f[x][y][z] = 0
            else:
                f[x][y][z] = 100
print(f)

[[[100.   0.   0.   0.   0.]
  [  0. 100. 100. 100. 100.]
  [100.   0. 100. 100.   0.]]

 [[  0. 100.   0.   0.   0.]
  [100.   0. 100. 100.   0.]
  [100. 100.   0. 100. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [75]:
# your code here
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("d_max is",d_max)
print("d_min is",d_min)
print("d_mean is",d_mean)

for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range (len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 25
            elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = 75
            elif d[x][y][z] == d_mean:
                d[x][y][z] = 50
            elif d[x][y][z] == d_min:
                f[x][y][z] = 0
            else:
                f[x][y][z] = 100
print(f)

d_max is 1.97066381
d_min is 1.00656599
d_mean is 1.6175069086666667
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [78]:
# your code here
f = np.empty((2, 3, 5), dtype = str)

for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range (len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = "B"
            elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = "D"
            elif d[x][y][z] == d_mean:
                d[x][y][z] = "C"
            elif d[x][y][z] == d_min:
                f[x][y][z] = "A"
            else:
                f[x][y][z] = "E"
print(f)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
