# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print(np.version)

<module 'numpy.version' from '/home/martin/.local/lib/python3.6/site-packages/numpy/version.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a=np.random.random((2,3,5))

In [9]:
# Method 2
a=np.random.random_matrix((2,3,5))

AttributeError: module 'numpy.random' has no attribute 'random_matrix'

In [ ]:
# Method 3


#### 4. Print *a*.


In [10]:
# your code here
a

array([[[0.9601651 , 0.7651005 , 0.32538072, 0.24198517, 0.35042921],
        [0.47565009, 0.97267844, 0.57669663, 0.19585353, 0.17910965],
        [0.37366461, 0.09313945, 0.14692684, 0.38590597, 0.10814498]],

       [[0.84437925, 0.92260791, 0.84182746, 0.17138498, 0.07594701],
        [0.35761226, 0.24504839, 0.88556561, 0.65327215, 0.73042823],
        [0.23332697, 0.84190582, 0.88934212, 0.97145652, 0.98982276]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [22]:
# your code here
b =np.ones((5,3,2))
#Cambio dimensiones requeridas para que al transponer las dimensiones queden correctas

#### 6. Print *b*.


In [23]:
# your code here
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [24]:
# your code here
if a.size==b.size:
    print('Son del mismo tamaño')
else:
    print('No son del mismo tamaño')

Son del mismo tamaño


#### 8. Are you able to add *a* and *b*? Why or why not?


In [25]:
# your answer here
sum_array=np.add(a,b)
#No, because both array have not shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [26]:
# your code here
c=np.transpose(b)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [27]:
# your code/answer here
d=np.add(a,c)
#Now the shapes are the same

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [29]:
# your code/answer here
print(a)
print(d)

[[[0.9601651  0.7651005  0.32538072 0.24198517 0.35042921]
  [0.47565009 0.97267844 0.57669663 0.19585353 0.17910965]
  [0.37366461 0.09313945 0.14692684 0.38590597 0.10814498]]

 [[0.84437925 0.92260791 0.84182746 0.17138498 0.07594701]
  [0.35761226 0.24504839 0.88556561 0.65327215 0.73042823]
  [0.23332697 0.84190582 0.88934212 0.97145652 0.98982276]]]
[[[1.9601651  1.7651005  1.32538072 1.24198517 1.35042921]
  [1.47565009 1.97267844 1.57669663 1.19585353 1.17910965]
  [1.37366461 1.09313945 1.14692684 1.38590597 1.10814498]]

 [[1.84437925 1.92260791 1.84182746 1.17138498 1.07594701]
  [1.35761226 1.24504839 1.88556561 1.65327215 1.73042823]
  [1.23332697 1.84190582 1.88934212 1.97145652 1.98982276]]]


In [30]:
#The array d has the a values plus 1

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
# your code here
e=np.multiply(a,c)
e

array([[[0.9601651 , 0.7651005 , 0.32538072, 0.24198517, 0.35042921],
        [0.47565009, 0.97267844, 0.57669663, 0.19585353, 0.17910965],
        [0.37366461, 0.09313945, 0.14692684, 0.38590597, 0.10814498]],

       [[0.84437925, 0.92260791, 0.84182746, 0.17138498, 0.07594701],
        [0.35761226, 0.24504839, 0.88556561, 0.65327215, 0.73042823],
        [0.23332697, 0.84190582, 0.88934212, 0.97145652, 0.98982276]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [33]:
# your code/answer here
#Yes, because we are multiplying each value by 1 (from c array)

### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [36]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max,d_min,d_mean)

1.9898227621853826 1.0759470053369 1.5268252777000402


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [38]:
# your code here
f=np.empty((2,3,5))
f

array([[[0.9601651 , 0.7651005 , 0.32538072, 0.24198517, 0.35042921],
        [0.47565009, 0.97267844, 0.57669663, 0.19585353, 0.17910965],
        [0.37366461, 0.09313945, 0.14692684, 0.38590597, 0.10814498]],

       [[0.84437925, 0.92260791, 0.84182746, 0.17138498, 0.07594701],
        [0.35761226, 0.24504839, 0.88556561, 0.65327215, 0.73042823],
        [0.23332697, 0.84190582, 0.88934212, 0.97145652, 0.98982276]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [44]:
# your code here
for x in range (np.shape(f)[0]):
    for y in range (np.shape(f)[1]):
        for z in range (np.shape(f)[2]):
            if d[x,y,z]>d_min and d[x,y,z]<d_mean:
                f[x,y,z]=25
            elif d[x,y,z]<d_max and d[x,y,z]>d_mean:
                f[x,y,z]=75
            elif d[x,y,z]==d_mean:
                f[x,y,z]=50
            elif d[x,y,z]==d_min:
                f[x,y,z]=0
            elif d[x,y,z]==d_max:
                f[x,y,z]=100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [46]:
# your code here
print (f)

[[[ 75.  75.  25.  25.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  75.  25.   0.]
  [ 25.  25.  75.  75.  75.]
  [ 25.  75.  75.  75. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [63]:
# your code here
f_str= np.empty((2,3,5), dtype=object)
for x in range (np.shape(f)[0]):
    for y in range (np.shape(f)[1]):
        for z in range (np.shape(f)[2]):
            if d[x,y,z]>d_min and d[x,y,z]<d_mean:
                f_str[x,y,z]="A"
            elif d[x,y,z]<d_max and d[x,y,z]>d_mean:
                f_str[x,y,z]="B"
            elif d[x,y,z]==d_mean:
                f_str[x,y,z]="C"
            elif d[x,y,z]==d_min:
                f_str[x,y,z]="D"
            elif d[x,y,z]==d_max:
                f_str[x,y,z]="E"

In [64]:
print(f_str)

[[['B' 'B' 'A' 'A' 'A']
  ['A' 'B' 'B' 'A' 'A']
  ['A' 'A' 'A' 'A' 'A']]

 [['B' 'B' 'B' 'A' 'D']
  ['A' 'A' 'B' 'B' 'B']
  ['A' 'B' 'B' 'B' 'E']]]
