# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
np.version.version

'1.17.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
a1 = np.random.random((2,3,5))
print (a1)

[[[0.63479762 0.69697411 0.76582238 0.38992623 0.2183214 ]
  [0.8928772  0.14510176 0.25490616 0.46570928 0.98680531]
  [0.88005954 0.39307049 0.45844099 0.7309187  0.85874002]]

 [[0.01805593 0.67263989 0.49861734 0.7918751  0.58499465]
  [0.48236232 0.99667569 0.57022863 0.03672344 0.62270127]
  [0.74734089 0.37583555 0.14152583 0.6558676  0.84066512]]]


In [7]:
# Method 2
#Con "dtype" puedo decirle si quiero int o float.
a2 = np.empty((2,3,5), dtype=int)
print(a2)

[[[4603892968220816677 4604453004185589302 4605073134331286210
   4600695906442618420 4597033877699499284]
  [4606217542374642710 4594395862125102196 4598263601000420712
   4602061092528051078 4607063571627015598]
  [4606102091186670690 4600752548430146938 4601930158646287850
   4604758749920977351 4605910062046506806]]

 [[4580861490036848608 4604233821046637791 4602653911440377720
   4605307796371562964 4603444382921567260]
  [4602361087027429114 4607152476088582078 4603311382474414581
   4585453226937778128 4603784013916346037]
  [4604906667828282877 4600442071338405126 4594267025684921436
   4604082749690549238 4605747257766103489]]]


In [8]:
#Method 3
#Con este consigo limitar el número más alto y salen enteros a partir del 0
a3 = np.random.randint(40, size=(2, 3, 5))
print(a3)

[[[16 17  8 12 13]
  [19  5  7  3 22]
  [29 28  4 36 26]]

 [[ 2 39 17 21  4]
  [32 29 29 25 38]
  [21 27 15  4 39]]]


In [9]:
# Method 4
#Con este consigo limitar el número más alto y salen enteros ordenados a partir del 0
a4 = np.arange(30).reshape(2,3,5)
print(a4)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### 4. Print *a*.


In [10]:
# your code here
print(a1)

[[[0.63479762 0.69697411 0.76582238 0.38992623 0.2183214 ]
  [0.8928772  0.14510176 0.25490616 0.46570928 0.98680531]
  [0.88005954 0.39307049 0.45844099 0.7309187  0.85874002]]

 [[0.01805593 0.67263989 0.49861734 0.7918751  0.58499465]
  [0.48236232 0.99667569 0.57022863 0.03672344 0.62270127]
  [0.74734089 0.37583555 0.14152583 0.6558676  0.84066512]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
# your code here
b = np.ones((5,3,2))

#### 6. Print *b*.


In [12]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here
#Con un operador booleano podemos comprobar si ambas matrizes tienen el mismo tamaño.
a1.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
# your answer here
np.add(a1, b)

#ValueError : operands could not be broadcast together with shapes (2,3,5) (5,2,3).
#Ambas matrices tienen el mismo tamaño total de valores* pero no la misma estructura, por lo tanto no es posible
#sumarlas.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [15]:
# your code here
c = np.transpose(b)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [16]:
# your code/answer here

d = np.add(a1, c)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
# your code/answer here
print(a1)
print(d)

#Al ser d una matriz que solo contiene 1, d es igual que a1 pero añadiendo 1 a todos los valores

[[[0.63479762 0.69697411 0.76582238 0.38992623 0.2183214 ]
  [0.8928772  0.14510176 0.25490616 0.46570928 0.98680531]
  [0.88005954 0.39307049 0.45844099 0.7309187  0.85874002]]

 [[0.01805593 0.67263989 0.49861734 0.7918751  0.58499465]
  [0.48236232 0.99667569 0.57022863 0.03672344 0.62270127]
  [0.74734089 0.37583555 0.14152583 0.6558676  0.84066512]]]
[[[1.63479762 1.69697411 1.76582238 1.38992623 1.2183214 ]
  [1.8928772  1.14510176 1.25490616 1.46570928 1.98680531]
  [1.88005954 1.39307049 1.45844099 1.7309187  1.85874002]]

 [[1.01805593 1.67263989 1.49861734 1.7918751  1.58499465]
  [1.48236232 1.99667569 1.57022863 1.03672344 1.62270127]
  [1.74734089 1.37583555 1.14152583 1.6558676  1.84066512]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
# your code here
e = np.multiply(a1, c)
print(e)

[[[0.63479762 0.69697411 0.76582238 0.38992623 0.2183214 ]
  [0.8928772  0.14510176 0.25490616 0.46570928 0.98680531]
  [0.88005954 0.39307049 0.45844099 0.7309187  0.85874002]]

 [[0.01805593 0.67263989 0.49861734 0.7918751  0.58499465]
  [0.48236232 0.99667569 0.57022863 0.03672344 0.62270127]
  [0.74734089 0.37583555 0.14152583 0.6558676  0.84066512]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
# your code/answer here
print(a1)
print(e)
#Son iguales. Multiplicar por 1 devuelve siempre el mismo valor.

[[[0.63479762 0.69697411 0.76582238 0.38992623 0.2183214 ]
  [0.8928772  0.14510176 0.25490616 0.46570928 0.98680531]
  [0.88005954 0.39307049 0.45844099 0.7309187  0.85874002]]

 [[0.01805593 0.67263989 0.49861734 0.7918751  0.58499465]
  [0.48236232 0.99667569 0.57022863 0.03672344 0.62270127]
  [0.74734089 0.37583555 0.14152583 0.6558676  0.84066512]]]
[[[0.63479762 0.69697411 0.76582238 0.38992623 0.2183214 ]
  [0.8928772  0.14510176 0.25490616 0.46570928 0.98680531]
  [0.88005954 0.39307049 0.45844099 0.7309187  0.85874002]]

 [[0.01805593 0.67263989 0.49861734 0.7918751  0.58499465]
  [0.48236232 0.99667569 0.57022863 0.03672344 0.62270127]
  [0.74734089 0.37583555 0.14152583 0.6558676  0.84066512]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [21]:
# your code here
print(d)
f = np.empty([2,3,5])
print(f)

[[[1.63479762 1.69697411 1.76582238 1.38992623 1.2183214 ]
  [1.8928772  1.14510176 1.25490616 1.46570928 1.98680531]
  [1.88005954 1.39307049 1.45844099 1.7309187  1.85874002]]

 [[1.01805593 1.67263989 1.49861734 1.7918751  1.58499465]
  [1.48236232 1.99667569 1.57022863 1.03672344 1.62270127]
  [1.74734089 1.37583555 1.14152583 1.6558676  1.84066512]]]
[[[1.63479762 1.69697411 1.76582238 1.38992623 1.2183214 ]
  [1.8928772  1.14510176 1.25490616 1.46570928 1.98680531]
  [1.88005954 1.39307049 1.45844099 1.7309187  1.85874002]]

 [[1.01805593 1.67263989 1.49861734 1.7918751  1.58499465]
  [1.48236232 1.99667569 1.57022863 1.03672344 1.62270127]
  [1.74734089 1.37583555 1.14152583 1.6558676  1.84066512]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [35]:
# your code here

for x in range(len(d)):
    for y in range(len(d[x])):
        for k in range (len(d[x][y])):
            if d[x][y][k] > d_min and d[x][y][k] < d_mean:
                f[x][y][k]= 25
            elif d[x][y][k] > d_mean and d[x][y][k] < d_max:
                f[x][y][k]= 75
            elif d[x][y][k] == d_mean: 
                f[x][y][k]= 50
            elif d[x][y][k] == d_max:
                f[x][y][k]= 100
            elif d[x][y][k] == d_min:
                f[x][y][k]= 0
                
print(f)

[[[1.63479762 1.69697411 1.76582238 1.38992623 1.2183214 ]
  [1.8928772  1.14510176 1.25490616 1.46570928 1.98680531]
  [1.88005954 1.39307049 1.45844099 1.7309187  1.85874002]]

 [[1.01805593 1.67263989 1.49861734 1.7918751  1.58499465]
  [1.48236232 1.99667569 1.57022863 1.03672344 1.62270127]
  [1.74734089 1.37583555 1.14152583 1.6558676  1.84066512]]]
1.996675691234479
1.018055933930036
1.5602860153833775
[[[ 75.  75.  75.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[  0.  75.  25.  75.  75.]
  [ 25. 100.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [36]:
# your code here
print(d)
print(f)

[[[1.63479762 1.69697411 1.76582238 1.38992623 1.2183214 ]
  [1.8928772  1.14510176 1.25490616 1.46570928 1.98680531]
  [1.88005954 1.39307049 1.45844099 1.7309187  1.85874002]]

 [[1.01805593 1.67263989 1.49861734 1.7918751  1.58499465]
  [1.48236232 1.99667569 1.57022863 1.03672344 1.62270127]
  [1.74734089 1.37583555 1.14152583 1.6558676  1.84066512]]]
[[[ 75.  75.  75.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[  0.  75.  25.  75.  75.]
  [ 25. 100.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [39]:
# your code here

f = np.empty([2,3,5], dtype = str)

for x in range(len(d)):
    for y in range(len(d[x])):
        for k in range (len(d[x][y])):
            if d[x][y][k] > d_min and d[x][y][k] < d_mean:
                f[x][y][k]= "B"
            elif d[x][y][k] > d_mean and d[x][y][k] < d_max:
                f[x][y][k]= "D"
            elif d[x][y][k] == d_mean: 
                f[x][y][k]= "C"
            elif d[x][y][k] == d_max:
                f[x][y][k]= "E"
            elif d[x][y][k] == d_min:
                f[x][y][k]= "A"
                
print(f)

[[['D' 'D' 'D' 'B' 'B']
  ['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']]

 [['A' 'D' 'B' 'D' 'D']
  ['B' 'E' 'D' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']]]
