# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [75]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [76]:
# your code here

np.version.version

'1.17.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [77]:
# Method 1

a = np.zeros((2,3,5))

In [78]:
# Method 2

a = np.random.random((2,3,5))

b = np.array(a)

print(b)

[[[0.12532103 0.98995293 0.15133425 0.09339042 0.88215894]
  [0.07956828 0.77410045 0.40922965 0.80557533 0.62781973]
  [0.2870458  0.18934345 0.68264005 0.3263454  0.38326642]]

 [[0.72156077 0.53296202 0.31161659 0.19377363 0.37741574]
  [0.83477165 0.22837669 0.14157125 0.91852826 0.149235  ]
  [0.56829226 0.75921457 0.36835628 0.45769648 0.2978517 ]]]


In [79]:
# Method 3

a = np.random.random((2,3,5))

#### 4. Print *a*.


In [80]:
# your code here
print(a)

[[[0.15929141 0.93008629 0.67409274 0.04932686 0.02366843]
  [0.96070536 0.96794842 0.94978144 0.05847438 0.88072725]
  [0.89470037 0.49649442 0.75751886 0.4939472  0.10490941]]

 [[0.85394423 0.59093231 0.35181266 0.02128838 0.93850498]
  [0.92756713 0.1788818  0.4008104  0.82141698 0.72837354]
  [0.82792946 0.66433236 0.49122496 0.60434131 0.68934344]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [81]:
# your code here

# Shouldn't it be (5,3,2) so we can add them in the exercise 10 after transposing? 

b = np.ones((5,3,2))

#### 6. Print *b*.


In [82]:
# your code here

print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [83]:
# your code here

np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [84]:
# your answer here

np.add(a,b) 

'''
The operation is only possible (doesnt result in shape mismatch error) in three cases:

- The arrays all have exactly the same shape.
- The arrays all have the same number of dimensions and the length of each dimensions is either a common length or 1.
- The arrays that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy property 2.

Even though a and b have the same dimensions, the length of each dimensions is not a common length nor 1.
'''

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [85]:
# your code here

c = np.transpose(b)

In [86]:
c.shape

(2, 3, 5)

In [87]:
a.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [92]:
# your code/answer here

'''
Both arrays have the same structure so the operation is possbile
'''

d = np.add(a,c)
d

array([[[1.15929141, 1.93008629, 1.67409274, 1.04932686, 1.02366843],
        [1.96070536, 1.96794842, 1.94978144, 1.05847438, 1.88072725],
        [1.89470037, 1.49649442, 1.75751886, 1.4939472 , 1.10490941]],

       [[1.85394423, 1.59093231, 1.35181266, 1.02128838, 1.93850498],
        [1.92756713, 1.1788818 , 1.4008104 , 1.82141698, 1.72837354],
        [1.82792946, 1.66433236, 1.49122496, 1.60434131, 1.68934344]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [93]:
np.shape(d)

(2, 3, 5)

In [94]:
# your code/answer here

np.add(a,d)

array([[[1.31858281, 2.86017258, 2.34818549, 1.09865372, 1.04733686],
        [2.92141071, 2.93589684, 2.89956289, 1.11694876, 2.7614545 ],
        [2.78940075, 1.99298884, 2.51503771, 1.98789439, 1.20981883]],

       [[2.70788846, 2.18186461, 1.70362532, 1.04257675, 2.87700997],
        [2.85513425, 1.35776359, 1.80162081, 2.64283395, 2.45674707],
        [2.65585892, 2.32866472, 1.98244992, 2.20868262, 2.37868689]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [95]:
# your code here

e = np.multiply(a,c)
e

array([[[0.15929141, 0.93008629, 0.67409274, 0.04932686, 0.02366843],
        [0.96070536, 0.96794842, 0.94978144, 0.05847438, 0.88072725],
        [0.89470037, 0.49649442, 0.75751886, 0.4939472 , 0.10490941]],

       [[0.85394423, 0.59093231, 0.35181266, 0.02128838, 0.93850498],
        [0.92756713, 0.1788818 , 0.4008104 , 0.82141698, 0.72837354],
        [0.82792946, 0.66433236, 0.49122496, 0.60434131, 0.68934344]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [97]:
# your code/answer here

'''
Since c is an array composed by all ones, the multiplication of a for c returns an equivalent array
'''

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [98]:
# your code here

d_max = np.max(d)
print(f'The max value of d is {d_max}')

d_min = np.min(d)
print(f'The min value of d is {d_min}')

d_mean = np.mean(d)
print(f'The mean value of d is {d_mean}')

The max value of d is 1.9679484202354238
The min value of d is 1.021288377162748
The mean value of d is 1.5830792259403599


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [99]:
# your code here

f = np.empty([2,3,5])
f

array([[[0.15929141, 0.93008629, 0.67409274, 0.04932686, 0.02366843],
        [0.96070536, 0.96794842, 0.94978144, 0.05847438, 0.88072725],
        [0.89470037, 0.49649442, 0.75751886, 0.4939472 , 0.10490941]],

       [[0.85394423, 0.59093231, 0.35181266, 0.02128838, 0.93850498],
        [0.92756713, 0.1788818 , 0.4008104 , 0.82141698, 0.72837354],
        [0.82792946, 0.66433236, 0.49122496, 0.60434131, 0.68934344]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [101]:
# your code here

def populate(d):

    for i in range(len(d)):
        
        for j in range(len(d[i])):
            
            for k in range(len(d[i][j])):
                
                x = d[i][j][k]
                if x > d_min and x < d_mean:
                    '''
                     if it's larger than d_min but smaller than d_mean, assign 25
                     '''
                    f[i][j][k] = 25      
                elif x > d_mean and x < d_max:
                    '''
                    if it's larger than d_mean but smaller than d_max, assign 75 
                    '''
                    f[i][j][k] = 75
                elif x == d_mean:
                    '''
                    if it's equals to d_mean, assign 50 
                    '''
                    f[i][j][k] = 50
                elif x == d_min:
                    '''
                    assign 0 to the corresponding value(s) in f for d_min 
                    '''
                    f[i][j][k] = 0
                else: 
                    '''
                    assign 100 to the corresponding value(s) in f for d_max in d
                    '''
                    f[i][j][k] = 100
    return f

print(populate(d))

[[[ 25.  75.  75.  25.  25.]
  [ 75. 100.  75.  25.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[ 75.  75.  25.   0.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [103]:
# your code here

print(f)

[[[ 25.  75.  75.  25.  25.]
  [ 75. 100.  75.  25.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[ 75.  75.  25.   0.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [107]:
# your code here

def populate(d):

    for i in range(len(d)):
        
        for j in range(len(d[i])):
            
            for k in range(len(d[i][j])):
                
                x = d[i][j][k]
                if x > d_min and x < d_mean:
                    '''
                     if to assign 25 = B
                     '''
                    f[i][j][k] = B      
                elif x > d_mean and x < d_max:
                    '''
                    if to assign 75 = D
                    '''
                    f[i][j][k] = D
                elif x == d_mean:
                    '''
                    if to assign 50 = C
                    '''
                    f[i][j][k] = C
                elif x == d_min:
                    '''
                    if to assign 0 = A 
                    '''
                    f[i][j][k] = A
                else: 
                    '''
                    if to assign 100 = E
                    '''
                    f[i][j][k] = E
    return f