# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.16.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [12]:
# Method 1
a = np.random.random((2,3,5))

In [11]:
# Method 2

In [ ]:
# Method 3


#### 4. Print *a*.


In [14]:
# your code here
print(a)

[[[0.5287709  0.90784675 0.88126471 0.4061359  0.58118915]
  [0.92953097 0.66537772 0.57700473 0.79652452 0.94210657]
  [0.90685162 0.43478688 0.63858149 0.60369385 0.64133011]]

 [[0.11156171 0.41445305 0.86069418 0.9434013  0.99018286]
  [0.17308764 0.54635999 0.26465351 0.24827573 0.8039832 ]
  [0.77106394 0.65373814 0.24181742 0.84167301 0.37031541]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [36]:
# your code here
b = np.ones((5,2,3), dtype = int)

#### 6. Print *b*.


In [37]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [30]:
# your code here

if np.size(a) == np.size(b):
    print("A y B tienen el mismo tamaño", np.size(a))
else:
    print("A y B no tiene el mismo tamaño", np.size(a))

A y B tienen el mismo tamaño 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [31]:
# your answer here
np.add(a, b)
#No, porque tienen columnas y filas diferentes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [39]:
# your code here
c = np.transpose(b,(1,2,0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [103]:
# your code/answer here
d = np.add(a,c)
# Funciona porque la matrix tiene la misma profundidad

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [104]:
# your code/answer here
print(a)
print(d)
#A* y D* tienen la misma dimencion pero D* es el resultado de A + C=(B)

[[[0.5287709  0.90784675 0.88126471 0.4061359  0.58118915]
  [0.92953097 0.66537772 0.57700473 0.79652452 0.94210657]
  [0.90685162 0.43478688 0.63858149 0.60369385 0.64133011]]

 [[0.11156171 0.41445305 0.86069418 0.9434013  0.99018286]
  [0.17308764 0.54635999 0.26465351 0.24827573 0.8039832 ]
  [0.77106394 0.65373814 0.24181742 0.84167301 0.37031541]]]
[[[1.5287709  1.90784675 1.88126471 1.4061359  1.58118915]
  [1.92953097 1.66537772 1.57700473 1.79652452 1.94210657]
  [1.90685162 1.43478688 1.63858149 1.60369385 1.64133011]]

 [[1.11156171 1.41445305 1.86069418 1.9434013  1.99018286]
  [1.17308764 1.54635999 1.26465351 1.24827573 1.8039832 ]
  [1.77106394 1.65373814 1.24181742 1.84167301 1.37031541]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [65]:
# your code here
e = np.multiply(a,c)
e

array([[[0.5287709 , 0.90784675, 0.88126471, 0.4061359 , 0.58118915],
        [0.92953097, 0.66537772, 0.57700473, 0.79652452, 0.94210657],
        [0.90685162, 0.43478688, 0.63858149, 0.60369385, 0.64133011]],

       [[0.11156171, 0.41445305, 0.86069418, 0.9434013 , 0.99018286],
        [0.17308764, 0.54635999, 0.26465351, 0.24827573, 0.8039832 ],
        [0.77106394, 0.65373814, 0.24181742, 0.84167301, 0.37031541]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [66]:
# your code/answer here
#E* y A* son iguales porque el restultado de x*1 da el mismo resultado
a

array([[[0.5287709 , 0.90784675, 0.88126471, 0.4061359 , 0.58118915],
        [0.92953097, 0.66537772, 0.57700473, 0.79652452, 0.94210657],
        [0.90685162, 0.43478688, 0.63858149, 0.60369385, 0.64133011]],

       [[0.11156171, 0.41445305, 0.86069418, 0.9434013 , 0.99018286],
        [0.17308764, 0.54635999, 0.26465351, 0.24827573, 0.8039832 ],
        [0.77106394, 0.65373814, 0.24181742, 0.84167301, 0.37031541]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [129]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max Value:", d_max )
print("Min Value:", d_min )
print("Mean Value:", d_mean )

Max Value: 1.990182862647369
Min Value: 1.1115617087303789
Mean Value: 1.622541898259438


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [127]:
# your code here
f = np.empty((2,3,5))
f

array([[[1.5287709 , 1.90784675, 1.88126471, 1.4061359 , 1.58118915],
        [1.92953097, 1.66537772, 1.57700473, 1.79652452, 1.94210657],
        [1.90685162, 1.43478688, 1.63858149, 1.60369385, 1.64133011]],

       [[1.11156171, 1.41445305, 1.86069418, 1.9434013 , 1.99018286],
        [1.17308764, 1.54635999, 1.26465351, 1.24827573, 1.8039832 ],
        [1.77106394, 1.65373814, 1.24181742, 1.84167301, 1.37031541]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [181]:
# your code here
for x in range(np.shape(f)[0]):
    for y in range(np.shape(f)[1]):
        for z in range(np.shape(f)[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 25
            elif d[x,y,z] == d_min:
                f[x,y,z] = 0
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100
print(f)

[[[ 25.  75.  75.  25.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  75.]]

 [[  0.  25.  75.  75. 100.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here