# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.16.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
a

array([[[0.95077752, 0.63562174, 0.35797415, 0.95824172, 0.94672259],
        [0.52554109, 0.43267998, 0.40024113, 0.26484155, 0.40354357],
        [0.85923553, 0.70431443, 0.36267395, 0.22132357, 0.28590317]],

       [[0.18347061, 0.99339805, 0.93212045, 0.72152553, 0.42570688],
        [0.31296066, 0.51509676, 0.41639017, 0.17808356, 0.16479856],
        [0.57547797, 0.6305426 , 0.78972963, 0.85303668, 0.93393888]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3), dtype=int)

#### 6. Print *b*.


In [8]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
print(np.shape(a))
print(np.shape(b))
np.shape(a) == np.shape(b)

(2, 3, 5)
(5, 2, 3)


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

No, because they don't have the same shape.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
c = b.transpose(1,2,0)
# Con los parámetros de transpose puedes jugar con la transposición
np.shape(c)

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
d = np.add(a,c)
d

array([[[1.95077752, 1.63562174, 1.35797415, 1.95824172, 1.94672259],
        [1.52554109, 1.43267998, 1.40024113, 1.26484155, 1.40354357],
        [1.85923553, 1.70431443, 1.36267395, 1.22132357, 1.28590317]],

       [[1.18347061, 1.99339805, 1.93212045, 1.72152553, 1.42570688],
        [1.31296066, 1.51509676, 1.41639017, 1.17808356, 1.16479856],
        [1.57547797, 1.6305426 , 1.78972963, 1.85303668, 1.93393888]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)
print("\n")
print(d)
# d = a+1 for every element in every matrix

[[[0.95077752 0.63562174 0.35797415 0.95824172 0.94672259]
  [0.52554109 0.43267998 0.40024113 0.26484155 0.40354357]
  [0.85923553 0.70431443 0.36267395 0.22132357 0.28590317]]

 [[0.18347061 0.99339805 0.93212045 0.72152553 0.42570688]
  [0.31296066 0.51509676 0.41639017 0.17808356 0.16479856]
  [0.57547797 0.6305426  0.78972963 0.85303668 0.93393888]]]


[[[1.95077752 1.63562174 1.35797415 1.95824172 1.94672259]
  [1.52554109 1.43267998 1.40024113 1.26484155 1.40354357]
  [1.85923553 1.70431443 1.36267395 1.22132357 1.28590317]]

 [[1.18347061 1.99339805 1.93212045 1.72152553 1.42570688]
  [1.31296066 1.51509676 1.41639017 1.17808356 1.16479856]
  [1.57547797 1.6305426  1.78972963 1.85303668 1.93393888]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = np.multiply(a,c)
e

array([[[0.95077752, 0.63562174, 0.35797415, 0.95824172, 0.94672259],
        [0.52554109, 0.43267998, 0.40024113, 0.26484155, 0.40354357],
        [0.85923553, 0.70431443, 0.36267395, 0.22132357, 0.28590317]],

       [[0.18347061, 0.99339805, 0.93212045, 0.72152553, 0.42570688],
        [0.31296066, 0.51509676, 0.41639017, 0.17808356, 0.16479856],
        [0.57547797, 0.6305426 , 0.78972963, 0.85303668, 0.93393888]]])

#### 13. Does *e* equal to *a*? Why or why not?


Yes, because every element is multiplied by 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [15]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9933980484516738
1.1647985625190147
1.5645304232359318


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [16]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [17]:
print(np.shape(d))
for x in range(np.shape(d)[0]):
    for y in range(np.shape(d)[1]):
        for z in range(np.shape(d)[2]):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 25
            if d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = 75
            if d[x][y][z] == d_mean:
                f[x][y][z] = 50
            if d[x][y][z] == d_min:
                f[x][y][z] = 0
            if d[x][y][z] == d_max:
                f[x][y][z] = 100


(2, 3, 5)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [18]:
print(d)
print("\n")
print(f)

[[[1.95077752 1.63562174 1.35797415 1.95824172 1.94672259]
  [1.52554109 1.43267998 1.40024113 1.26484155 1.40354357]
  [1.85923553 1.70431443 1.36267395 1.22132357 1.28590317]]

 [[1.18347061 1.99339805 1.93212045 1.72152553 1.42570688]
  [1.31296066 1.51509676 1.41639017 1.17808356 1.16479856]
  [1.57547797 1.6305426  1.78972963 1.85303668 1.93393888]]]


[[[ 75.  75.  25.  75.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  75.  25.  25.  25.]]

 [[ 25. 100.  75.  75.  25.]
  [ 25.  25.  25.  25.   0.]
  [ 75.  75.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [19]:
# primero tengo que convertir el array de destino al tipo del que voy a meter elementos
# el de origen no lo toco porque si no no me hace la comparación numérica
f = np.array(f,dtype=str)

In [20]:
for x in range(np.shape(d)[0]):
    for y in range(np.shape(d)[1]):
        for z in range(np.shape(d)[2]):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 'B'
            if d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = 'D'
            if d[x][y][z] == d_mean:
                f[x][y][z] = 'C'
            if d[x][y][z] == d_min:
                f[x][y][z] = 'A'
            if d[x][y][z] == d_max:
                f[x][y][z] = 'E'

In [21]:
print(d)
print("\n")
print(f)

[[[1.95077752 1.63562174 1.35797415 1.95824172 1.94672259]
  [1.52554109 1.43267998 1.40024113 1.26484155 1.40354357]
  [1.85923553 1.70431443 1.36267395 1.22132357 1.28590317]]

 [[1.18347061 1.99339805 1.93212045 1.72152553 1.42570688]
  [1.31296066 1.51509676 1.41639017 1.17808356 1.16479856]
  [1.57547797 1.6305426  1.78972963 1.85303668 1.93393888]]]


[[['D' 'D' 'B' 'D' 'D']
  ['B' 'B' 'B' 'B' 'B']
  ['D' 'D' 'B' 'B' 'B']]

 [['B' 'E' 'D' 'D' 'B']
  ['B' 'B' 'B' 'B' 'A']
  ['D' 'D' 'D' 'D' 'D']]]
