# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [13]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [37]:
# your code here
np.version.version

'1.16.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
# Method 1
a = np.random.random((2,3,5))


In [16]:
# Method 2


In [17]:
# Method 3

#### 4. Print *a*.


In [18]:
# your code here
a

array([[[0.69714898, 0.27764835, 0.74944122, 0.90111403, 0.62087421],
        [0.04593133, 0.27161122, 0.74038188, 0.23932111, 0.93195042],
        [0.1787235 , 0.83068416, 0.88341162, 0.21896231, 0.3383236 ]],

       [[0.93663857, 0.93654604, 0.78569937, 0.3140918 , 0.29882457],
        [0.12048776, 0.62515517, 0.81198343, 0.93939029, 0.21274488],
        [0.53469594, 0.41487146, 0.77306647, 0.43029999, 0.32671739]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [20]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
# your code here
b == a

/home/gus/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [22]:
# your answer here
np.add((a,b))
# differents sizes

ValueError: invalid number of arguments

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
# your code here

c = b.transpose([1,2,0])
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here
print(a)

print(d)

[[[0.69714898 0.27764835 0.74944122 0.90111403 0.62087421]
  [0.04593133 0.27161122 0.74038188 0.23932111 0.93195042]
  [0.1787235  0.83068416 0.88341162 0.21896231 0.3383236 ]]

 [[0.93663857 0.93654604 0.78569937 0.3140918  0.29882457]
  [0.12048776 0.62515517 0.81198343 0.93939029 0.21274488]
  [0.53469594 0.41487146 0.77306647 0.43029999 0.32671739]]]
[[[1.69714898 1.27764835 1.74944122 1.90111403 1.62087421]
  [1.04593133 1.27161122 1.74038188 1.23932111 1.93195042]
  [1.1787235  1.83068416 1.88341162 1.21896231 1.3383236 ]]

 [[1.93663857 1.93654604 1.78569937 1.3140918  1.29882457]
  [1.12048776 1.62515517 1.81198343 1.93939029 1.21274488]
  [1.53469594 1.41487146 1.77306647 1.43029999 1.32671739]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here
e = np.multiply(a,c)
e

array([[[0.69714898, 0.27764835, 0.74944122, 0.90111403, 0.62087421],
        [0.04593133, 0.27161122, 0.74038188, 0.23932111, 0.93195042],
        [0.1787235 , 0.83068416, 0.88341162, 0.21896231, 0.3383236 ]],

       [[0.93663857, 0.93654604, 0.78569937, 0.3140918 , 0.29882457],
        [0.12048776, 0.62515517, 0.81198343, 0.93939029, 0.21274488],
        [0.53469594, 0.41487146, 0.77306647, 0.43029999, 0.32671739]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [27]:
# your code/answer here
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [34]:
# your code here
d_max = np.max(d)
print(d_max)
d_mean = np.mean(d)
print(d_mean)
d_min = np.min(d)
print(d_min)


1.9393902869404855
1.5462247023344566
1.0459313300606676


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here




In [55]:
f= np.empty((2,3,5))
f

array([[[75.,  0., 75., 75., 75.],
        [ 0.,  0., 75.,  0., 75.],
        [ 0., 75., 75.,  0.,  0.]],

       [[75., 75., 75.,  0.,  0.],
        [ 0., 75., 75.,  0.,  0.],
        [ 0.,  0., 75.,  0.,  0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [59]:
# your code here



for i_lst,lst in enumerate(d):
    for i_num,num in enumerate(lst):
        for i_x,x in enumerate(num):
            if x > d_mean and x < d_max:
                f[i_lst,i_num,i_x] = 75
            elif x == d_mean:
                f[i_lst,i_num,i_x] = 50
            elif x == d_min:
                f[i_lst,i_num,i_x] = 0
            elif x == d_max:
                f[i_lst,i_num,i_x] = 100
            elif x > d_min and x < d_mean:
                f[i_lst,i_num,i_x] = 25
f

                        


array([[[ 75.,  25.,  75.,  75.,  75.],
        [  0.,  25.,  75.,  25.,  75.],
        [ 25.,  75.,  75.,  25.,  25.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  75.,  75., 100.,  25.],
        [ 25.,  25.,  75.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [33]:
# your code here
d

array([[[1.69714898, 1.27764835, 1.74944122, 1.90111403, 1.62087421],
        [1.04593133, 1.27161122, 1.74038188, 1.23932111, 1.93195042],
        [1.1787235 , 1.83068416, 1.88341162, 1.21896231, 1.3383236 ]],

       [[1.93663857, 1.93654604, 1.78569937, 1.3140918 , 1.29882457],
        [1.12048776, 1.62515517, 1.81198343, 1.93939029, 1.21274488],
        [1.53469594, 1.41487146, 1.77306647, 1.43029999, 1.32671739]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [67]:
# your code here
for i_lst,lst in enumerate(d):
    for i_num,num in enumerate(lst):
        for i_x,x in enumerate(num):
            if x > d_mean and x < d_max:
                f[i_lst,i_num,i_x] = "D"
            elif x == d_mean:
                f[i_lst,i_num,i_x] = "C"
            elif x == d_min:
                f[i_lst,i_num,i_x] = "A"
            elif x == d_max:
                f[i_lst,i_num,i_x] = "E"
            elif x > d_min and x < d_mean:
                f[i_lst,i_num,i_x] = "B"

ValueError: could not convert string to float: 'D'