# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.03573429, 0.78469817, 0.43270338, 0.86358749, 0.59246295],
        [0.28983914, 0.43580972, 0.87791288, 0.44817635, 0.8783098 ],
        [0.66056522, 0.58688644, 0.23657001, 0.99729407, 0.18163403]],

       [[0.9970542 , 0.69959341, 0.29387825, 0.42135682, 0.10880356],
        [0.23844013, 0.70592295, 0.34704996, 0.88328183, 0.13452338],
        [0.99602694, 0.95016541, 0.04399039, 0.98003547, 0.42058688]]])

In [6]:
a = np.random.random((2,3,5))
b = np.array(a)
a

array([[[0.56122691, 0.95978302, 0.32054114, 0.161524  , 0.23388373],
        [0.859055  , 0.01059614, 0.18466605, 0.6767    , 0.84901014],
        [0.56917937, 0.36916539, 0.37681121, 0.19097449, 0.61013815]],

       [[0.06185611, 0.07376844, 0.26178218, 0.39552926, 0.76643758],
        [0.17046337, 0.17339001, 0.95143395, 0.74627083, 0.15893353],
        [0.06412279, 0.39633266, 0.69927519, 0.78303142, 0.68410713]]])

In [ ]:
# Method 3


#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[0.56122691 0.95978302 0.32054114 0.161524   0.23388373]
  [0.859055   0.01059614 0.18466605 0.6767     0.84901014]
  [0.56917937 0.36916539 0.37681121 0.19097449 0.61013815]]

 [[0.06185611 0.07376844 0.26178218 0.39552926 0.76643758]
  [0.17046337 0.17339001 0.95143395 0.74627083 0.15893353]
  [0.06412279 0.39633266 0.69927519 0.78303142 0.68410713]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,3,2))

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
# your answer here

np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

In [ ]:
'''
To add arrays a & b we need the same shape and dimensions. For this reason we have a valueError.
'''

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
# your code here
c = np.transpose(b)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [18]:
# your code/answer here
d = np.add(a,c)
d

array([[[1.56122691, 1.95978302, 1.32054114, 1.161524  , 1.23388373],
        [1.859055  , 1.01059614, 1.18466605, 1.6767    , 1.84901014],
        [1.56917937, 1.36916539, 1.37681121, 1.19097449, 1.61013815]],

       [[1.06185611, 1.07376844, 1.26178218, 1.39552926, 1.76643758],
        [1.17046337, 1.17339001, 1.95143395, 1.74627083, 1.15893353],
        [1.06412279, 1.39633266, 1.69927519, 1.78303142, 1.68410713]]])

In [ ]:
'''
In this case we have that both arrays have the same shape and dimensions
'''

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
# your code/answer here
print(a)

[[[0.56122691 0.95978302 0.32054114 0.161524   0.23388373]
  [0.859055   0.01059614 0.18466605 0.6767     0.84901014]
  [0.56917937 0.36916539 0.37681121 0.19097449 0.61013815]]

 [[0.06185611 0.07376844 0.26178218 0.39552926 0.76643758]
  [0.17046337 0.17339001 0.95143395 0.74627083 0.15893353]
  [0.06412279 0.39633266 0.69927519 0.78303142 0.68410713]]]


In [22]:
print(d)

[[[1.56122691 1.95978302 1.32054114 1.161524   1.23388373]
  [1.859055   1.01059614 1.18466605 1.6767     1.84901014]
  [1.56917937 1.36916539 1.37681121 1.19097449 1.61013815]]

 [[1.06185611 1.07376844 1.26178218 1.39552926 1.76643758]
  [1.17046337 1.17339001 1.95143395 1.74627083 1.15893353]
  [1.06412279 1.39633266 1.69927519 1.78303142 1.68410713]]]


In [ ]:
'''
I can observe how array d is the same array than a but +1 in each term. Like if we add a&d.
'''

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [23]:
# your code here
e = np.multiply(a,c)
e

array([[[0.56122691, 0.95978302, 0.32054114, 0.161524  , 0.23388373],
        [0.859055  , 0.01059614, 0.18466605, 0.6767    , 0.84901014],
        [0.56917937, 0.36916539, 0.37681121, 0.19097449, 0.61013815]],

       [[0.06185611, 0.07376844, 0.26178218, 0.39552926, 0.76643758],
        [0.17046337, 0.17339001, 0.95143395, 0.74627083, 0.15893353],
        [0.06412279, 0.39633266, 0.69927519, 0.78303142, 0.68410713]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [24]:
# your code/answer here
print(a)

[[[0.56122691 0.95978302 0.32054114 0.161524   0.23388373]
  [0.859055   0.01059614 0.18466605 0.6767     0.84901014]
  [0.56917937 0.36916539 0.37681121 0.19097449 0.61013815]]

 [[0.06185611 0.07376844 0.26178218 0.39552926 0.76643758]
  [0.17046337 0.17339001 0.95143395 0.74627083 0.15893353]
  [0.06412279 0.39633266 0.69927519 0.78303142 0.68410713]]]


In [25]:
print(e)

[[[0.56122691 0.95978302 0.32054114 0.161524   0.23388373]
  [0.859055   0.01059614 0.18466605 0.6767     0.84901014]
  [0.56917937 0.36916539 0.37681121 0.19097449 0.61013815]]

 [[0.06185611 0.07376844 0.26178218 0.39552926 0.76643758]
  [0.17046337 0.17339001 0.95143395 0.74627083 0.15893353]
  [0.06412279 0.39633266 0.69927519 0.78303142 0.68410713]]]


In [ ]:
'''
array c is the transpose of array b composed by ones, if we multiply a&c to obtain e we have the array a
'''

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
# your code here
d_max = np.max(d)
print(f'The max value of d is {d_max}')

d_min = np.min(d)
print(f'The min value of d is {d_min}')

d_mean = np.mean(d)
print(f'The mean value of d is {d_mean}')

The max value of d is 1.9597830195767463
The min value of d is 1.0105961359518687
The mean value of d is 1.4439996393093686


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [27]:
# your code here
f = np.empty([2,3,5])
f

array([[[0.56122691, 0.95978302, 0.32054114, 0.161524  , 0.23388373],
        [0.859055  , 0.01059614, 0.18466605, 0.6767    , 0.84901014],
        [0.56917937, 0.36916539, 0.37681121, 0.19097449, 0.61013815]],

       [[0.06185611, 0.07376844, 0.26178218, 0.39552926, 0.76643758],
        [0.17046337, 0.17339001, 0.95143395, 0.74627083, 0.15893353],
        [0.06412279, 0.39633266, 0.69927519, 0.78303142, 0.68410713]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [33]:
# your code here

def pop(d):
    for x in range(len(d)):
        for y in range(len(d[x])):
            for z in range (len(d[x][y])):
                
                x= d[x][y][z]
                
                if x>d_min and x<d_mean:
                    f[x][y][z] = 25
                
                elif x>d_mean and x<d_max:
                    f[x][y][z] = 75
                
                elif x == d_mean:
                    f[x][y][z] = 50
                    
                elif x == d_min:
                    f[x][y][z] = 0
                
                else: 
                    f[x][y][z] = 100
                
    return f


In [34]:
print(pop(d))
#no entiendo porque me da este error

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [35]:
# your code here
print(f)

[[[0.56122691 0.95978302 0.32054114 0.161524   0.23388373]
  [0.859055   0.01059614 0.18466605 0.6767     0.84901014]
  [0.56917937 0.36916539 0.37681121 0.19097449 0.61013815]]

 [[0.06185611 0.07376844 0.26178218 0.39552926 0.76643758]
  [0.17046337 0.17339001 0.95143395 0.74627083 0.15893353]
  [0.06412279 0.39633266 0.69927519 0.78303142 0.68410713]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here
#no time! i will do it these next days