# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a = np.random.rand(2,3,5)
a

array([[[0.25337112, 0.43529172, 0.21960268, 0.91619944, 0.65044147],
        [0.34331553, 0.64744952, 0.48783694, 0.77798332, 0.03071858],
        [0.27940933, 0.17281608, 0.07294435, 0.87943474, 0.69486075]],

       [[0.94492577, 0.37304138, 0.06470798, 0.6511091 , 0.76015556],
        [0.89247379, 0.34662719, 0.13481407, 0.85695184, 0.21487786],
        [0.10687237, 0.56607192, 0.08050354, 0.5875455 , 0.25248449]]])

In [8]:
# Method 2
a1 = np.random.random_sample((2,3,5))
a1

array([[[0.6560362 , 0.41546026, 0.25893093, 0.95523374, 0.60286842],
        [0.48546471, 0.1640636 , 0.96078189, 0.50489893, 0.86750946],
        [0.30778606, 0.89602537, 0.62208772, 0.42865074, 0.10179769]],

       [[0.13695146, 0.52968149, 0.07810297, 0.43882939, 0.61847273],
        [0.6568384 , 0.64683084, 0.31249458, 0.62538995, 0.78987802],
        [0.2657642 , 0.61240587, 0.58477687, 0.4030445 , 0.17044751]]])

In [9]:
# Method 3
a2 = np.empty(shape=(2,3,5), dtype=float)
a2

array([[[0.6560362 , 0.41546026, 0.25893093, 0.95523374, 0.60286842],
        [0.48546471, 0.1640636 , 0.96078189, 0.50489893, 0.86750946],
        [0.30778606, 0.89602537, 0.62208772, 0.42865074, 0.10179769]],

       [[0.13695146, 0.52968149, 0.07810297, 0.43882939, 0.61847273],
        [0.6568384 , 0.64683084, 0.31249458, 0.62538995, 0.78987802],
        [0.2657642 , 0.61240587, 0.58477687, 0.4030445 , 0.17044751]]])

In [10]:
# Extra method
a3 = np.random.randn(2,3,5)
a3

array([[[-1.25252867, -0.17439691, -0.10298595,  0.29581594,
          0.61152035],
        [ 0.72758467, -1.3778674 , -0.29891502, -2.10725117,
         -0.14147039],
        [ 2.02864975,  1.0506193 , -0.52630549,  0.18809631,
          0.45211596]],

       [[ 0.01550451,  1.77554232,  0.09662217, -0.21835299,
          0.85204245],
        [ 1.6535337 , -0.66971078, -0.01793358, -0.4557716 ,
         -2.57448129],
        [-0.81544851, -1.62028421, -0.95296578, -0.82976145,
          0.46002792]]])

#### 4. Print *a*.


In [12]:
# your code here
print(f'np.array a is: {a}')

np.array a is: [[[0.25337112 0.43529172 0.21960268 0.91619944 0.65044147]
  [0.34331553 0.64744952 0.48783694 0.77798332 0.03071858]
  [0.27940933 0.17281608 0.07294435 0.87943474 0.69486075]]

 [[0.94492577 0.37304138 0.06470798 0.6511091  0.76015556]
  [0.89247379 0.34662719 0.13481407 0.85695184 0.21487786]
  [0.10687237 0.56607192 0.08050354 0.5875455  0.25248449]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [14]:
# your code here
print(f'np.array b is: {b}')

np.array b is: [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [16]:
# your answer here
result = a + b
# It is not possible to sum the arrays because they don't have the same shapes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [17]:
# your code here
c = np.transpose(b, axes=(1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
# your code/answer here
d = a + c
d

array([[[1.25337112, 1.43529172, 1.21960268, 1.91619944, 1.65044147],
        [1.34331553, 1.64744952, 1.48783694, 1.77798332, 1.03071858],
        [1.27940933, 1.17281608, 1.07294435, 1.87943474, 1.69486075]],

       [[1.94492577, 1.37304138, 1.06470798, 1.6511091 , 1.76015556],
        [1.89247379, 1.34662719, 1.13481407, 1.85695184, 1.21487786],
        [1.10687237, 1.56607192, 1.08050354, 1.5875455 , 1.25248449]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
# your code/answer here
print(f'np.array a is: {a}')
print(f'np.array d is: {d}')

#every value of d is equal to a+1

np.array a is: [[[0.25337112 0.43529172 0.21960268 0.91619944 0.65044147]
  [0.34331553 0.64744952 0.48783694 0.77798332 0.03071858]
  [0.27940933 0.17281608 0.07294435 0.87943474 0.69486075]]

 [[0.94492577 0.37304138 0.06470798 0.6511091  0.76015556]
  [0.89247379 0.34662719 0.13481407 0.85695184 0.21487786]
  [0.10687237 0.56607192 0.08050354 0.5875455  0.25248449]]]
np.array d is: [[[1.25337112 1.43529172 1.21960268 1.91619944 1.65044147]
  [1.34331553 1.64744952 1.48783694 1.77798332 1.03071858]
  [1.27940933 1.17281608 1.07294435 1.87943474 1.69486075]]

 [[1.94492577 1.37304138 1.06470798 1.6511091  1.76015556]
  [1.89247379 1.34662719 1.13481407 1.85695184 1.21487786]
  [1.10687237 1.56607192 1.08050354 1.5875455  1.25248449]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
# your code here
e = a * c

print(f'np.array e is: {e}')

np.array e is: [[[0.25337112 0.43529172 0.21960268 0.91619944 0.65044147]
  [0.34331553 0.64744952 0.48783694 0.77798332 0.03071858]
  [0.27940933 0.17281608 0.07294435 0.87943474 0.69486075]]

 [[0.94492577 0.37304138 0.06470798 0.6511091  0.76015556]
  [0.89247379 0.34662719 0.13481407 0.85695184 0.21487786]
  [0.10687237 0.56607192 0.08050354 0.5875455  0.25248449]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [31]:
# your code/answer here
print(f'np.array a is: {a}')
print(f'np.array e is: {e}')
# a is equal to e because very value in a is multiplied by 1

np.array a is: [[[0.25337112 0.43529172 0.21960268 0.91619944 0.65044147]
  [0.34331553 0.64744952 0.48783694 0.77798332 0.03071858]
  [0.27940933 0.17281608 0.07294435 0.87943474 0.69486075]]

 [[0.94492577 0.37304138 0.06470798 0.6511091  0.76015556]
  [0.89247379 0.34662719 0.13481407 0.85695184 0.21487786]
  [0.10687237 0.56607192 0.08050354 0.5875455  0.25248449]]]
np.array e is: [[[0.25337112 0.43529172 0.21960268 0.91619944 0.65044147]
  [0.34331553 0.64744952 0.48783694 0.77798332 0.03071858]
  [0.27940933 0.17281608 0.07294435 0.87943474 0.69486075]]

 [[0.94492577 0.37304138 0.06470798 0.6511091  0.76015556]
  [0.89247379 0.34662719 0.13481407 0.85695184 0.21487786]
  [0.10687237 0.56607192 0.08050354 0.5875455  0.25248449]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
# your code here
d_max = np.max(d)
d_max

1.9449257748886173

In [25]:
d_min = np.min(d)
d_min

1.0307185762815134

In [26]:
d_mean = np.mean(d)
d_mean

1.4564945976085006

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [34]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [35]:
# your code here
print(f'np.array f is: {f}')

np.array f is: [[[ 25.  25.  25.  75.  75.]
  [ 25.  75.  75.  75.   0.]
  [ 25.  25.  25.  75.  75.]]

 [[100.  25.  25.  75.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  75.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [38]:
# your code here

letters = d.astype(str)
letters[(d > d_min) & (d < d_mean)] = "B"
letters[(d > d_mean) & (d < d_max)] = "D"
letters[d == d_mean] = "C"
letters[d == d_min] = "A"
letters[d == d_max] = "E"


In [40]:
print(f'The transformed array is: {letters}')

The transformed array is: [[['B' 'B' 'B' 'D' 'D']
  ['B' 'D' 'D' 'D' 'A']
  ['B' 'B' 'B' 'D' 'D']]

 [['E' 'B' 'B' 'D' 'D']
  ['D' 'B' 'B' 'D' 'B']
  ['B' 'D' 'B' 'D' 'B']]]
