# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [85]:
# your code here

import numpy as np
import random as rd

#### 2. Print your NumPy version.

In [86]:
# your code here

np.version

<module 'numpy.version' from '/Users/miquicampuzano/opt/anaconda3/lib/python3.8/site-packages/numpy/version.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [87]:
# Method 1
a = np.random.rand(2,)

a

array([0.15977281, 0.61463862])

In [88]:
# Method 2

a = np.random.randint(1,100,(2,3,5))

a

array([[[74, 18, 56, 11, 69],
        [52, 11, 59,  9, 21],
        [32, 59, 21, 67, 55]],

       [[43, 51,  6, 84, 72],
        [13, 37, 69, 19, 82],
        [71, 22, 31, 15, 65]]])

In [89]:
# Method 3

a = np.random.random_integers(1,1000,(2,3,5))
a

array([[[580, 437, 527, 187, 646],
        [916, 684, 380, 642, 947],
        [674, 536, 623,  21, 172]],

       [[827, 723, 871, 134, 161],
        [439,  54, 224, 899, 825],
        [626, 864, 532, 407, 702]]])

#### 4. Print *a*.


In [90]:
# your code here
a

array([[[580, 437, 527, 187, 646],
        [916, 684, 380, 642, 947],
        [674, 536, 623,  21, 172]],

       [[827, 723, 871, 134, 161],
        [439,  54, 224, 899, 825],
        [626, 864, 532, 407, 702]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [91]:
# your code here

b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [97]:
# your code here
b.shape

(5, 2, 3)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [93]:
# your code here

a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [94]:
# your answer here

# No, because they are of different shapes

c = a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [98]:
# your code here

c = np.transpose(b, axes=(1,2,0))

c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [99]:
# your code/answer here

# It works because they are of the same size.

d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [101]:
# your code/answer here

# It is different because in d we are adding a matrx wirth ones. Thus, it has one more value in each cell.

print(a)

print(d)

[[[580 437 527 187 646]
  [916 684 380 642 947]
  [674 536 623  21 172]]

 [[827 723 871 134 161]
  [439  54 224 899 825]
  [626 864 532 407 702]]]
[[[581. 438. 528. 188. 647.]
  [917. 685. 381. 643. 948.]
  [675. 537. 624.  22. 173.]]

 [[828. 724. 872. 135. 162.]
  [440.  55. 225. 900. 826.]
  [627. 865. 533. 408. 703.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [102]:
# your code here

e = a * c

e

array([[[580., 437., 527., 187., 646.],
        [916., 684., 380., 642., 947.],
        [674., 536., 623.,  21., 172.]],

       [[827., 723., 871., 134., 161.],
        [439.,  54., 224., 899., 825.],
        [626., 864., 532., 407., 702.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [103]:
# your code/answer here

# Yes, because we are multiplying each cell by one.
print(a)

print(e)

[[[580 437 527 187 646]
  [916 684 380 642 947]
  [674 536 623  21 172]]

 [[827 723 871 134 161]
  [439  54 224 899 825]
  [626 864 532 407 702]]]
[[[580. 437. 527. 187. 646.]
  [916. 684. 380. 642. 947.]
  [674. 536. 623.  21. 172.]]

 [[827. 723. 871. 134. 161.]
  [439.  54. 224. 899. 825.]
  [626. 864. 532. 407. 702.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [104]:
# your code here
print(f"Max is {d.max()}")
print(f"Min is {d.min()}")
print(f"Mean is {d.mean()}")

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

Max is 948.0
Min is 22.0
Mean is 543.0


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [105]:
# your code here

f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [117]:
# your code here

(n,m,p) = d.shape

for i in range(n):
    for k in range(m):
        for j in range(p):
            if d[i,k,j] > d_min and d[i,k,j] < d_mean:
                f[i,k,j] = 25
            elif d[i,k,j] > d_mean and d[i,k,j] < d_max:
                f[i,k,j] = 75
            elif d[i,k,j] == d_mean:
                f[i,k,j] = 50
            elif d[i,k,j] == d_min:
                f[i,k,j] = 0
            elif d[i,k,j] == d_max:
                f[i,k,j] = 100

array([[[ 75.,  25.,  25.,  25.,  75.],
        [ 75.,  75.,  25.,  75., 100.],
        [ 75.,  25.,  75.,   0.,  25.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  75.,  75.],
        [ 75.,  75.,  25.,  25.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [118]:
# your code here

print(d)

print(f)

[[[581. 438. 528. 188. 647.]
  [917. 685. 381. 643. 948.]
  [675. 537. 624.  22. 173.]]

 [[828. 724. 872. 135. 162.]
  [440.  55. 225. 900. 826.]
  [627. 865. 533. 408. 703.]]]
[[[ 75.  25.  25.  25.  75.]
  [ 75.  75.  25.  75. 100.]
  [ 75.  25.  75.   0.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [122]:
# your code here

f = np.empty((2,3,5), dtype = str)

for i in range(n):
    for k in range(m):
        for j in range(p):
            if d[i,k,j] > d_min and d[i,k,j] < d_mean:
                f[i,k,j] = "A"
            elif d[i,k,j] > d_mean and d[i,k,j] < d_max:
                f[i,k,j] = "B"
            elif d[i,k,j] == d_mean:
                f[i,k,j] = "C"
            elif d[i,k,j] == d_min:
                f[i,k,j] = "D"
            elif d[i,k,j] == d_max:
                f[i,k,j] = "E"


In [123]:
print(f)

[[['B' 'A' 'A' 'A' 'B']
  ['B' 'B' 'A' 'B' 'E']
  ['B' 'A' 'B' 'D' 'A']]

 [['B' 'B' 'B' 'A' 'A']
  ['A' 'A' 'A' 'B' 'B']
  ['B' 'B' 'A' 'A' 'B']]]
