# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.27541678 0.72457167 0.83903072 0.12500636 0.15634535]
  [0.71327345 0.70944182 0.99926794 0.8552511  0.44824109]
  [0.87980515 0.58049082 0.11290801 0.51390935 0.30020199]]

 [[0.35669122 0.73318703 0.78425101 0.29590872 0.67078351]
  [0.7953285  0.24042286 0.15838169 0.50962518 0.97610681]
  [0.72281839 0.82514224 0.44269705 0.2720306  0.77945736]]]


In [4]:
# Method 2
a = np.random.rand(2,3,5)
print(a)

[[[0.14994729 0.77107476 0.83011959 0.3720137  0.64264477]
  [0.54358261 0.25265682 0.18703612 0.66785964 0.32592139]
  [0.02244905 0.51089713 0.6490647  0.60015992 0.80409599]]

 [[0.53330137 0.25759266 0.16090102 0.95150858 0.74787174]
  [0.08497834 0.36447035 0.49880268 0.91168048 0.32828948]
  [0.86812292 0.26034901 0.52495216 0.84685682 0.60333264]]]


In [5]:
# Method 3
a = np.random.randint(10,size=(2,3,5))
print(a)

[[[4 4 0 2 9]
  [1 5 4 9 1]
  [8 3 2 6 9]]

 [[0 9 3 9 6]
  [6 4 7 8 6]
  [3 8 7 9 4]]]


#### 4. Print *a*.


In [6]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size == b.size)
print(a.shape == b.shape)

True
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
"""
No se pueden sumar porque aunque tengan el mismo numero de elementos,
las dimensiones de las matrices son diferentes"""
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = np.transpose(b,(1,2,0))
print(c.shape)
c = np.reshape(b, (2,3,5))
print(c.shape)

(2, 3, 5)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)
d = a + c
print(d)

[[[ 5.  5.  1.  3. 10.]
  [ 2.  6.  5. 10.  2.]
  [ 9.  4.  3.  7. 10.]]

 [[ 1. 10.  4. 10.  7.]
  [ 7.  5.  8.  9.  7.]
  [ 4.  9.  8. 10.  5.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
"""
Suma 1 a todos los elementos de a.
"""

[[[4 4 0 2 9]
  [1 5 4 9 1]
  [8 3 2 6 9]]

 [[0 9 3 9 6]
  [6 4 7 8 6]
  [3 8 7 9 4]]]
[[[ 5.  5.  1.  3. 10.]
  [ 2.  6.  5. 10.  2.]
  [ 9.  4.  3.  7. 10.]]

 [[ 1. 10.  4. 10.  7.]
  [ 7.  5.  8.  9.  7.]
  [ 4.  9.  8. 10.  5.]]]


'\nSuma 1 a todos los elementos de a.\n'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)
e = a * c
print(e)

[[[4. 4. 0. 2. 9.]
  [1. 5. 4. 9. 1.]
  [8. 3. 2. 6. 9.]]

 [[0. 9. 3. 9. 6.]
  [6. 4. 7. 8. 6.]
  [3. 8. 7. 9. 4.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
"""
a and e are equal because we are multiplying each element of a by one
"""

'\na and e are equal because we are multiplying each element of a by one\n'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

10.0
1.0
6.2


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
def populate(d):
    for i in range(len(d)):
        for j in range(len(d[i])):
            for k in range(len(d[i][j])):
                x = d[i][j][k]
                if x > d_min and x < d_mean:
                    f[i][j][k] = 25
                elif x > d_mean and x < d_max:
                    f[i][j][k] = 75
                elif x == d_mean:
                    f[i][j][k] = 50
                elif x == d_min:
                    f[i][j][k] = 0
                else: 
                    f[i][j][k] = 100
    return f
print(populate(d))

[[[ 25.  25.   0.  25. 100.]
  [ 25.  25.  25. 100.  25.]
  [ 75.  25.  25.  75. 100.]]

 [[  0. 100.  25. 100.  75.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  75.  75. 100.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
# your code here
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)
print(populate(d))

1.97066381
1.00656599
1.6175069086666667
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here
g = np.empty([2,3,5] , dtype = str)
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            x = d[i][j][k]
            if x > d_min and x < d_mean:
                g[i][j][k] = 'B'
            elif x > d_mean and x < d_max:
                g[i][j][k] = 'D'
            elif x == d_mean:
                g[i][j][k] = 'C'
            elif x == d_min:
                g[i][j][k] = 'A'
            else: 
                g[i][j][k] = 'E'
print(g)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
