# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [6]:
# your code here
np.version.version

'1.16.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [110]:
# Method 1
a = np.random.random((2,3,5))

In [111]:
# Method 2 
a2 = np.random.random_sample((2,3,5))

In [112]:
# Method 3
a3 = np.random.ranf((2,3,5))

#### 4. Print *a*.


In [34]:
# your code here
print(a)

[[[0.8195593  0.39316531 0.29052204 0.13548875 0.99324615]
  [0.91767015 0.20834979 0.76320285 0.57956028 0.11652092]
  [0.82232013 0.88275694 0.29206053 0.05354096 0.49950926]]

 [[0.03215634 0.89796362 0.74729752 0.84696609 0.33031836]
  [0.59211717 0.45083085 0.34323    0.613381   0.97868993]
  [0.24142315 0.25616233 0.20332866 0.80002167 0.35947544]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [35]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [36]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [37]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [39]:
# your answer here

#We can't add a and b, because they have the same size but not the same shape
a.shape == b.shape

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [42]:
# your code here
c = b.transpose(1,2,0)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [96]:
# your code/answer here
d = np.add(a,c)
#Now the shapes of a and c are the same
a.shape == c.shape

True

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [97]:
# your code/answer here
print(a)
print(d)

#The array d is the same as the a plus 1 in each item"
np.array_equal(d,a+1)

[[[0.8195593  0.39316531 0.29052204 0.13548875 0.99324615]
  [0.91767015 0.20834979 0.76320285 0.57956028 0.11652092]
  [0.82232013 0.88275694 0.29206053 0.05354096 0.49950926]]

 [[0.03215634 0.89796362 0.74729752 0.84696609 0.33031836]
  [0.59211717 0.45083085 0.34323    0.613381   0.97868993]
  [0.24142315 0.25616233 0.20332866 0.80002167 0.35947544]]]
[[[1.8195593  1.39316531 1.29052204 1.13548875 1.99324615]
  [1.91767015 1.20834979 1.76320285 1.57956028 1.11652092]
  [1.82232013 1.88275694 1.29206053 1.05354096 1.49950926]]

 [[1.03215634 1.89796362 1.74729752 1.84696609 1.33031836]
  [1.59211717 1.45083085 1.34323    1.613381   1.97868993]
  [1.24142315 1.25616233 1.20332866 1.80002167 1.35947544]]]


True

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [70]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [71]:
# your code/answer here
print(np.array_equal(e,a))

#Yes because multiplying all the cells by one, do not transform the numbers

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [98]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [101]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [102]:
# your code here
k = d.shape

for i in range(0,k[0]):
    for j in range(0,k[1]):
        for z in range(0,k[2]):
            if d[i,j,z] > d_min and d[i,j,z] < d_mean:
                f[i,j,z] = 25
            elif d[i,j,z] > d_mean and d[i,j,z] < d_max:
                f[i,j,z] = 75
            elif d[i,j,z] == d_mean:
                f[i,j,z] = 50   
            elif d[i,j,z] == d_min:
                f[i,j,z]= 0 
            elif d[i,j,z] == d_max:
                f[i,j,z] = 100 

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [103]:
# your code here
print(d)
print(f)
#Yes. We have one min (0), one max (1) and a varied numbers of 75 and 25, there is no mean

[[[1.8195593  1.39316531 1.29052204 1.13548875 1.99324615]
  [1.91767015 1.20834979 1.76320285 1.57956028 1.11652092]
  [1.82232013 1.88275694 1.29206053 1.05354096 1.49950926]]

 [[1.03215634 1.89796362 1.74729752 1.84696609 1.33031836]
  [1.59211717 1.45083085 1.34323    1.613381   1.97868993]
  [1.24142315 1.25616233 1.20332866 1.80002167 1.35947544]]]
[[[ 75.  25.  25.  25. 100.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  25.  25.  25.]]

 [[  0.  75.  75.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [104]:
# your code here
f = np.empty((2,3,5), dtype=str)
k = d.shape
for i in range(0,k[0]):
    for j in range(0,k[1]):
        for z in range(0,k[2]):
            if d[i,j,z] > d_min and d[i,j,z] < d_mean:
                f[i,j,z] = 'B'
            elif d[i,j,z] > d_mean and d[i,j,z] < d_max:
                f[i,j,z] = 'D'
            elif d[i,j,z] == d_mean:
                f[i,j,z] = 'C'   
            elif d[i,j,z] == d_min:
                f[i,j,z] = 'A' 
            elif d[i,j,z] == d_max:
                f[i,j,z] = 'E' 

In [105]:
print(f)

[[['D' 'B' 'B' 'B' 'E']
  ['D' 'B' 'D' 'D' 'B']
  ['D' 'D' 'B' 'B' 'B']]

 [['A' 'D' 'D' 'D' 'B']
  ['D' 'B' 'B' 'D' 'D']
  ['B' 'B' 'B' 'D' 'B']]]
