# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.rand(2,3,5)

In [4]:
# Method 2

a_1 = np.random.randint(1,100,(2,3,5))

In [5]:
# Method 3

a_2 = np.random.randn(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[5.80346530e-01 2.35816852e-01 8.25556032e-01 8.53668689e-01
   1.95065324e-01]
  [1.35793618e-01 7.07217099e-01 4.58387245e-05 7.72576217e-01
   2.03180077e-01]
  [8.51483540e-01 8.11012462e-01 7.00730562e-01 5.29948269e-01
   4.81081850e-01]]

 [[4.46634130e-01 4.43028190e-01 7.38739293e-01 7.87373434e-01
   8.95130801e-01]
  [2.07499495e-01 2.64440302e-02 5.08116205e-01 5.73966832e-02
   1.92307216e-01]
  [6.04806774e-01 2.50811809e-01 8.47200163e-01 6.66174605e-01
   7.88525950e-01]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

if a.shape == b.shape:
    print('Yes, a and b do have the same size.')
else:
    print('No, a and b do not have the same size.')

No, a and b do not have the same size.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

# We can't add a and b because they have different sizes. To be able to do so, we must transpose one of them first.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = a + c
print(d)

# It works now because a and c have the same size.

[[[1.58034653 1.23581685 1.82555603 1.85366869 1.19506532]
  [1.13579362 1.7072171  1.00004584 1.77257622 1.20318008]
  [1.85148354 1.81101246 1.70073056 1.52994827 1.48108185]]

 [[1.44663413 1.44302819 1.73873929 1.78737343 1.8951308 ]
  [1.20749949 1.02644403 1.5081162  1.05739668 1.19230722]
  [1.60480677 1.25081181 1.84720016 1.6661746  1.78852595]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(f'{a} \n \n {d}')

# d array have the same values in a array + 1

[[[5.80346530e-01 2.35816852e-01 8.25556032e-01 8.53668689e-01
   1.95065324e-01]
  [1.35793618e-01 7.07217099e-01 4.58387245e-05 7.72576217e-01
   2.03180077e-01]
  [8.51483540e-01 8.11012462e-01 7.00730562e-01 5.29948269e-01
   4.81081850e-01]]

 [[4.46634130e-01 4.43028190e-01 7.38739293e-01 7.87373434e-01
   8.95130801e-01]
  [2.07499495e-01 2.64440302e-02 5.08116205e-01 5.73966832e-02
   1.92307216e-01]
  [6.04806774e-01 2.50811809e-01 8.47200163e-01 6.66174605e-01
   7.88525950e-01]]] 
 
 [[[1.58034653 1.23581685 1.82555603 1.85366869 1.19506532]
  [1.13579362 1.7072171  1.00004584 1.77257622 1.20318008]
  [1.85148354 1.81101246 1.70073056 1.52994827 1.48108185]]

 [[1.44663413 1.44302819 1.73873929 1.78737343 1.8951308 ]
  [1.20749949 1.02644403 1.5081162  1.05739668 1.19230722]
  [1.60480677 1.25081181 1.84720016 1.6661746  1.78852595]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = a * c
print(e)

[[[5.80346530e-01 2.35816852e-01 8.25556032e-01 8.53668689e-01
   1.95065324e-01]
  [1.35793618e-01 7.07217099e-01 4.58387245e-05 7.72576217e-01
   2.03180077e-01]
  [8.51483540e-01 8.11012462e-01 7.00730562e-01 5.29948269e-01
   4.81081850e-01]]

 [[4.46634130e-01 4.43028190e-01 7.38739293e-01 7.87373434e-01
   8.95130801e-01]
  [2.07499495e-01 2.64440302e-02 5.08116205e-01 5.73966832e-02
   1.92307216e-01]
  [6.04806774e-01 2.50811809e-01 8.47200163e-01 6.66174605e-01
   7.88525950e-01]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

a == e

# They are equal because c is an array of ones.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty(d.shape)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

for value in range(len(d)):
    for value2 in range(len(d[value])):
        for value3 in range(len(d[value][value2])):
            if d[value][value2][value3] > d_min and d[value][value2][value3] < d_mean:
                f[value][value2][value3] = 25
            elif d[value][value2][value3] > d_mean and d[value][value2][value3] < d_max:
                f[value][value2][value3] = 75
            elif d[value][value2][value3] == d_mean:
                f[value][value2][value3] = 50
            elif d[value][value2][value3] == d_min:
                f[value][value2][value3] = 0
            elif d[value][value2][value3] == d_max:
                f[value][value2][value3] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(f'd is \n {d} \n \n and f is \n {f}')

d is 
 [[[1.58034653 1.23581685 1.82555603 1.85366869 1.19506532]
  [1.13579362 1.7072171  1.00004584 1.77257622 1.20318008]
  [1.85148354 1.81101246 1.70073056 1.52994827 1.48108185]]

 [[1.44663413 1.44302819 1.73873929 1.78737343 1.8951308 ]
  [1.20749949 1.02644403 1.5081162  1.05739668 1.19230722]
  [1.60480677 1.25081181 1.84720016 1.6661746  1.78852595]]] 
 
 and f is 
 [[[ 75.  25.  75.  75.  25.]
  [ 25.  75.   0.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  75. 100.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here

g = f.astype(str)

for value in range(len(d)):
    for value2 in range(len(d[value])):
        for value3 in range(len(d[value][value2])):
            if d[value][value2][value3] > d_min and d[value][value2][value3] < d_mean:
                g[value][value2][value3] = 'B'
            elif d[value][value2][value3] > d_mean and d[value][value2][value3] < d_max:
                g[value][value2][value3] = 'D'
            elif d[value][value2][value3] == d_mean:
                g[value][value2][value3] = 'C'
            elif d[value][value2][value3] == d_min:
                g[value][value2][value3] = 'A'
            elif d[value][value2][value3] == d_max:
                g[value][value2][value3] = 'E'

print(g)

[[['D' 'B' 'D' 'D' 'B']
  ['B' 'D' 'A' 'D' 'B']
  ['D' 'D' 'D' 'D' 'B']]

 [['B' 'B' 'D' 'D' 'E']
  ['B' 'B' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]]
