In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [8]:
# your code here
np.version.version

'1.17.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [18]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.07929771 0.98465016 0.55760834 0.25093112 0.98898993]
  [0.53899574 0.61753057 0.6921061  0.23668187 0.7921209 ]
  [0.31454251 0.78667226 0.41396666 0.40840653 0.17402584]]

 [[0.26897995 0.26539128 0.32765379 0.93686523 0.86008989]
  [0.50449452 0.36260011 0.70015601 0.49701694 0.93441008]
  [0.32715568 0.70930469 0.47004171 0.21444193 0.7489525 ]]]


In [19]:
# Method 2
b = np.array(a) 
print(b)

[[[0.07929771 0.98465016 0.55760834 0.25093112 0.98898993]
  [0.53899574 0.61753057 0.6921061  0.23668187 0.7921209 ]
  [0.31454251 0.78667226 0.41396666 0.40840653 0.17402584]]

 [[0.26897995 0.26539128 0.32765379 0.93686523 0.86008989]
  [0.50449452 0.36260011 0.70015601 0.49701694 0.93441008]
  [0.32715568 0.70930469 0.47004171 0.21444193 0.7489525 ]]]


In [21]:
# Method 3
print(np.zeros((2,3,5)))
print(np.ones((2,3,5)))
print(np.full((2,3,5), 2))

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]]


#### 4. Print *a*.


In [22]:
# your code here
print(a)

[[[0.07929771 0.98465016 0.55760834 0.25093112 0.98898993]
  [0.53899574 0.61753057 0.6921061  0.23668187 0.7921209 ]
  [0.31454251 0.78667226 0.41396666 0.40840653 0.17402584]]

 [[0.26897995 0.26539128 0.32765379 0.93686523 0.86008989]
  [0.50449452 0.36260011 0.70015601 0.49701694 0.93441008]
  [0.32715568 0.70930469 0.47004171 0.21444193 0.7489525 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [66]:
# your code here
b = np.ones((5,3,2))

#### 6. Print *b*.


In [67]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [68]:
# your code here
if np.size(a) == b.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [147]:
# your answer here
#we can't add them because they aren't the same size
print(np.add(a, b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [70]:
# your code 
c = np.transpose(b)
print(c)
c.shape
a.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [73]:
# your code/answer here
d = np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [75]:
# your code/answer here ... it's random a + 1
print(a)
print(d)

array([[[0.07929771, 0.98465016, 0.55760834, 0.25093112, 0.98898993],
        [0.53899574, 0.61753057, 0.6921061 , 0.23668187, 0.7921209 ],
        [0.31454251, 0.78667226, 0.41396666, 0.40840653, 0.17402584]],

       [[0.26897995, 0.26539128, 0.32765379, 0.93686523, 0.86008989],
        [0.50449452, 0.36260011, 0.70015601, 0.49701694, 0.93441008],
        [0.32715568, 0.70930469, 0.47004171, 0.21444193, 0.7489525 ]]])

[[[1.07929771 1.98465016 1.55760834 1.25093112 1.98898993]
  [1.53899574 1.61753057 1.6921061  1.23668187 1.7921209 ]
  [1.31454251 1.78667226 1.41396666 1.40840653 1.17402584]]

 [[1.26897995 1.26539128 1.32765379 1.93686523 1.86008989]
  [1.50449452 1.36260011 1.70015601 1.49701694 1.93441008]
  [1.32715568 1.70930469 1.47004171 1.21444193 1.7489525 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [77]:
# your code here
e = np.multiply(a, c)

array([[[0.07929771, 0.98465016, 0.55760834, 0.25093112, 0.98898993],
        [0.53899574, 0.61753057, 0.6921061 , 0.23668187, 0.7921209 ],
        [0.31454251, 0.78667226, 0.41396666, 0.40840653, 0.17402584]],

       [[0.26897995, 0.26539128, 0.32765379, 0.93686523, 0.86008989],
        [0.50449452, 0.36260011, 0.70015601, 0.49701694, 0.93441008],
        [0.32715568, 0.70930469, 0.47004171, 0.21444193, 0.7489525 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [78]:
# your code/answer here... c = 1.. a = a * 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [83]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [89]:
# your code here
f = np.empty([2, 3, 5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [145]:
def xxx(array):
    for y in range(len(array)):
        for x in range(len(array[y])):
            for z in range(len(array[y][x])):
                if d_mean > array[y][x][z] > d_min:
                    f[y][x][z] = 25
                elif d_max > array[y][x][z] > d_mean:
                    f[y][x][z] = 75
                elif array[y][x][z] == d_mean:
                    f[y][x][z] = 50
                elif array[y][x][z] == d_min:
                    f[y][x][z] = 0
                elif array[y][x][z] == d_max:
                    f[y][x][z] = 100
    return f
f = np.empty([2, 3, 5])
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [146]:
# your code here
print(xxx(d))

[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [143]:
# your code here
def xxx(array):
    for y in range(len(array)):
        for x in range(len(array[y])):
            for z in range(len(array[y][x])):
                if d_mean > array[y][x][z] > d_min:
                    f[y][x][z] = "B"
                elif d_max > array[y][x][z] > d_mean:
                    f[y][x][z] = "D"
                elif array[y][x][z] == d_mean:
                    f[y][x][z] = "C"
                elif array[y][x][z] == d_min:
                    f[y][x][z] = "A"
                elif array[y][x][z] == d_max:
                    f[y][x][z] = "E"
    return f

In [144]:
f = np.empty([2, 3, 5], dtype = str ) 
print(xxx(d))

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
