# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [38]:
import numpy as np

#### 2. Print your NumPy version.

In [39]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [40]:
a = np.random.rand(2,3,5) #esta es una 2x3x5 3-dimensional con random decimal numbers

In [41]:
a1= np.random.randint(100, size=(2,3,5)) #me da una array de 2X3X5  de valores random hasta el 100

In [42]:
a2 = np.random.choice(range(100),size=(2,3,5))#me da una array de 2X3X5  de valores random hasta el 100

#### 4. Print *a*.


In [43]:
print(a)

[[[0.77546235 0.57459737 0.13202967 0.16145498 0.82717185]
  [0.26544046 0.10455671 0.21047503 0.89354482 0.49231677]
  [0.92455927 0.67530858 0.47980314 0.71228911 0.30078312]]

 [[0.04533151 0.33799023 0.29705747 0.13487047 0.33880033]
  [0.27173362 0.53917759 0.04670183 0.95149237 0.71083384]
  [0.72125757 0.81810779 0.77336337 0.81259576 0.77246608]]]


In [44]:
print(a1)

[[[72 45 40 82 84]
  [14 60 73  4 50]
  [59  1 97 51 27]]

 [[13 83 73 77 93]
  [94 80 24 74 12]
  [86 65 75  6 48]]]


In [45]:
print(a2)

[[[30 11 95 65 47]
  [71 34  1 65 92]
  [30 10 75 84 18]]

 [[62 91 43 74 32]
  [ 0 89 36 76 68]
  [31 16 94 91 14]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [46]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [47]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [48]:
a.size == b.size #size is the number of elements in an array

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [49]:
#we can't add them up because eventhough the size is the same the shape is different 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [50]:
c = b.transpose(1,2,0) # axis 0 era 5, axis 1 era 2 y axis 2 era 3 y ahora ha pasado a ser axis 0 = 2, axis 1 = 3 y axis 2 = 5 (si lo he entendido bien) 

In [51]:
c.shape

(2, 3, 5)

In [52]:
a.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [53]:
d= a+c # ahora si que podemos porqué a y c tienen la misma shape 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [54]:
print(a) 

[[[0.77546235 0.57459737 0.13202967 0.16145498 0.82717185]
  [0.26544046 0.10455671 0.21047503 0.89354482 0.49231677]
  [0.92455927 0.67530858 0.47980314 0.71228911 0.30078312]]

 [[0.04533151 0.33799023 0.29705747 0.13487047 0.33880033]
  [0.27173362 0.53917759 0.04670183 0.95149237 0.71083384]
  [0.72125757 0.81810779 0.77336337 0.81259576 0.77246608]]]


In [55]:
print(d) # "d" es el resultado de sumar 1 a cada elemento de "a"

[[[1.77546235 1.57459737 1.13202967 1.16145498 1.82717185]
  [1.26544046 1.10455671 1.21047503 1.89354482 1.49231677]
  [1.92455927 1.67530858 1.47980314 1.71228911 1.30078312]]

 [[1.04533151 1.33799023 1.29705747 1.13487047 1.33880033]
  [1.27173362 1.53917759 1.04670183 1.95149237 1.71083384]
  [1.72125757 1.81810779 1.77336337 1.81259576 1.77246608]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [56]:
e = a*c 

In [57]:
print(e)

[[[0.77546235 0.57459737 0.13202967 0.16145498 0.82717185]
  [0.26544046 0.10455671 0.21047503 0.89354482 0.49231677]
  [0.92455927 0.67530858 0.47980314 0.71228911 0.30078312]]

 [[0.04533151 0.33799023 0.29705747 0.13487047 0.33880033]
  [0.27173362 0.53917759 0.04670183 0.95149237 0.71083384]
  [0.72125757 0.81810779 0.77336337 0.81259576 0.77246608]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [58]:
e == a #son iguales porqué e es el resultado de multiplicar los elementos de "a" por "1", ya uqe "c" es un array que solo contiene "1"

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [59]:
d_max = np.max(d)

In [60]:
print(d_max)

1.9514923671867956


In [61]:
d_min = np.min(d)

In [62]:
print(d_min)

1.0453315104983214


In [63]:
d_mean=np.mean(d)

In [64]:
print(d_mean)

1.503385768175105


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [65]:
f = np.empty(d.shape)

In [66]:
print(f)

[[[0.2618443  0.16653621 0.80276794 0.37238452 0.39862805]
  [0.104913   0.01199931 0.68130465 0.13171045 0.20886444]
  [0.3923402  0.08905105 0.21020504 0.17006699 0.88764231]]

 [[0.22046962 0.96778001 0.36961109 0.49310209 0.90442274]
  [0.22023969 0.04931798 0.07813234 0.94276456 0.33456351]
  [0.84311389 0.34490488 0.61360952 0.27837026 0.91047572]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [69]:
(n,m,p) = d.shape
for i in range(n):
    for j in range(m):
        for k in range(p):
            if d_min < d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [70]:
f #yes it worked

array([[[ 75.,  75.,  25.,  25.,  75.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  25.,  75.,  25.]],

       [[  0.,  25.,  25.,  25.,  25.],
        [ 25.,  75.,  25., 100.,  75.],
        [ 75.,  75.,  75.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.