# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
# Method 1
a = np.random.random((2,3,5))

In [10]:
# Method 2


In [ ]:
# Method 3

#### 4. Print *a*.


In [12]:
# your code here
a

array([[[0.20453519, 0.54512518, 0.33725602, 0.81625928, 0.43867523],
        [0.23347587, 0.29596243, 0.90655115, 0.33138019, 0.76765576],
        [0.33920512, 0.54966935, 0.21823426, 0.93568448, 0.70681416]],

       [[0.84975759, 0.24082336, 0.93134039, 0.82255011, 0.81079703],
        [0.90674822, 0.54481513, 0.04909891, 0.68020432, 0.50861045],
        [0.43951814, 0.29084351, 0.77222019, 0.94042876, 0.86051662]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [14]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [17]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [22]:
# your answer here

#If shape of two arrays are not same, that is a.shape != b.shape, they must be broadcastable to a common shape 
#(which may be the shape of one or the other)

a.shape != b.shape

#Addition not possible
a_and_b = np.add(a, b) #getting error


True

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [36]:
# your code here

c = np.transpose(b, (1, 2, 0))
c

print(c.shape)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [39]:
# your code/answer here

#it will work now because both arrays have the same shape

print(a.shape)
print(c.shape)
d = np.add(a, c)

(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [46]:
# your code/answer here
print(a)
print(d)

#since c array is containing only values "1", the d array is exactly as array a where each element is 1 value higher

d == a+1

[[[0.20453519 0.54512518 0.33725602 0.81625928 0.43867523]
  [0.23347587 0.29596243 0.90655115 0.33138019 0.76765576]
  [0.33920512 0.54966935 0.21823426 0.93568448 0.70681416]]

 [[0.84975759 0.24082336 0.93134039 0.82255011 0.81079703]
  [0.90674822 0.54481513 0.04909891 0.68020432 0.50861045]
  [0.43951814 0.29084351 0.77222019 0.94042876 0.86051662]]]
[[[1.20453519 1.54512518 1.33725602 1.81625928 1.43867523]
  [1.23347587 1.29596243 1.90655115 1.33138019 1.76765576]
  [1.33920512 1.54966935 1.21823426 1.93568448 1.70681416]]

 [[1.84975759 1.24082336 1.93134039 1.82255011 1.81079703]
  [1.90674822 1.54481513 1.04909891 1.68020432 1.50861045]
  [1.43951814 1.29084351 1.77222019 1.94042876 1.86051662]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [48]:
# your code here
e = np.multiply(a,c)
e

array([[[0.20453519, 0.54512518, 0.33725602, 0.81625928, 0.43867523],
        [0.23347587, 0.29596243, 0.90655115, 0.33138019, 0.76765576],
        [0.33920512, 0.54966935, 0.21823426, 0.93568448, 0.70681416]],

       [[0.84975759, 0.24082336, 0.93134039, 0.82255011, 0.81079703],
        [0.90674822, 0.54481513, 0.04909891, 0.68020432, 0.50861045],
        [0.43951814, 0.29084351, 0.77222019, 0.94042876, 0.86051662]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [54]:
# your code/answer here
np.array_equal(e, a)

#yes, it's equal, because the shape and elements are equal. e array is multiplied by array c which elemtns are "1", 
#multiplication by 1 doesn't change the value



True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [62]:
# your code here

d_max = np.amax(d)
d_max

d_min = np.amin(d)
d_min

d_mean = np.mean(d)
d_mean

1.9404287557363116

1.0490989126804653

1.5758252128190269

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [149]:
# your code here

f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [171]:
# your code here

#For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f
# Assign 0 to the corresponding value(s) in f for d_min in d
# Assign 100 to the corresponding value(s) in f for d_max in d


for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 25
            elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = 75
            elif d[x][y][z] == d_mean:
                f[x][y][z] = 50
            elif d[x][y][z] == d_min:
                f[x][y][z] = 0
            elif d[x][y][z] == d_max:
                f[x][y][z] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [173]:
# your code here
print(d)
print(f)

[[[1.20453519 1.54512518 1.33725602 1.81625928 1.43867523]
  [1.23347587 1.29596243 1.90655115 1.33138019 1.76765576]
  [1.33920512 1.54966935 1.21823426 1.93568448 1.70681416]]

 [[1.84975759 1.24082336 1.93134039 1.82255011 1.81079703]
  [1.90674822 1.54481513 1.04909891 1.68020432 1.50861045]
  [1.43951814 1.29084351 1.77222019 1.94042876 1.86051662]]]
[[[ 25.  25.  25.  75.  25.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  25.  25.  75.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 75.  25.   0.  75.  25.]
  [ 25.  25.  75. 100.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [176]:
# your code here

g = np.empty((2,3,5), dtype=str)  #create empty array with type 'string'

for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                g[x][y][z] = "B"
            elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                g[x][y][z] = "D"
            elif d[x][y][z] == d_mean:
                g[x][y][z] = "C"
            elif d[x][y][z] == d_min:
                g[x][y][z] = "A"
            elif d[x][y][z] == d_max:
                g[x][y][z] = "E"
print(g)

[[['B' 'B' 'B' 'D' 'B']
  ['B' 'B' 'D' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']]

 [['D' 'B' 'D' 'D' 'D']
  ['D' 'B' 'A' 'D' 'B']
  ['B' 'B' 'D' 'E' 'D']]]
