# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [249]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [250]:
# your code here

print(np.__version__)

1.17.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [251]:
# Method 1

a = np.random.random((2, 3, 5))
print(a)

[[[0.01042386 0.60222484 0.13863902 0.78242599 0.66747235]
  [0.99408251 0.01330262 0.56930953 0.53004968 0.77131408]
  [0.7795981  0.37212895 0.8361423  0.21523804 0.19163755]]

 [[0.20523398 0.78108949 0.22851268 0.37358585 0.20732939]
  [0.15271141 0.53981642 0.15132512 0.35939217 0.80886519]
  [0.92256238 0.12795171 0.83543513 0.05591957 0.24453589]]]


In [252]:
# Method 2

a2 = np.random.random_sample((2, 3, 5))

print (a2)

[[[0.40794193 0.15992697 0.35693156 0.94355267 0.48501645]
  [0.44023198 0.40550351 0.54287109 0.51523687 0.61077106]
  [0.54695587 0.70917603 0.34816724 0.14773209 0.11819416]]

 [[0.49291815 0.56661184 0.62687234 0.02793391 0.92448152]
  [0.90486802 0.30738799 0.72900896 0.6238926  0.94439446]
  [0.63145437 0.17192114 0.30634583 0.59521535 0.07138886]]]


In [253]:
# Method 3

a3 = np.random.rand(2,3,5)

print (a3)


[[[0.59270568 0.49892367 0.2246331  0.77177916 0.40972398]
  [0.78326065 0.62603052 0.44139674 0.86515703 0.35432997]
  [0.59459555 0.54105491 0.95184464 0.49212464 0.83404627]]

 [[0.05242787 0.83877836 0.91761896 0.10011562 0.57492152]
  [0.45616678 0.54246129 0.41046197 0.7513318  0.84107878]
  [0.12294769 0.26662959 0.71573968 0.23298506 0.29057562]]]


#### 4. Print *a*.


In [254]:
# your code here

print(a)
print("")
print("Numero de dimensiones de a -", a.ndim) # Para comprobar que es de 3 dimensiones
print("")
print("Shape de a -", a.shape) # Para comprobar el shape es correcto

[[[0.01042386 0.60222484 0.13863902 0.78242599 0.66747235]
  [0.99408251 0.01330262 0.56930953 0.53004968 0.77131408]
  [0.7795981  0.37212895 0.8361423  0.21523804 0.19163755]]

 [[0.20523398 0.78108949 0.22851268 0.37358585 0.20732939]
  [0.15271141 0.53981642 0.15132512 0.35939217 0.80886519]
  [0.92256238 0.12795171 0.83543513 0.05591957 0.24453589]]]

Numero de dimensiones de a - 3

Shape de a - (2, 3, 5)


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [255]:
# your code here

b = np.ones((5, 2, 3))

print("Numero de dimensiones de b -", b.ndim) # Para comprobar que es de 3 dimensiones
print("")
print("Shape de b -", b.shape) # Para comprobar el shape es correcto

Numero de dimensiones de b - 3

Shape de b - (5, 2, 3)


#### 6. Print *b*.


In [256]:
# your code here

print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [257]:
# your code here

# Llamaremos al size de cada una (número total de elementos de cada n-dimensional array) y los comparamos.

if b.size == a.size:
    print ("True")
else:
    print ("False")

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [258]:
# your answer here

# No permite add a y b porque no tienen el mismo shape.

np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [259]:
# your code here

c = np.transpose(b,(1,2,0)) 

# Con (b,(1,2,0)) defino el orden en el que se colocarán los axes de b al hacer transpose.
# Es decir, en la posición 0 queremos que el 2, que era la posición. 
# En la posición 1, queremos el 3, que era la posición 2.
# En la posición 3, queremos el 5, que era la posición 0.

print(c)

c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [260]:
# your code/answer here

d = np.add(a, c)

print(d)

# Ahora funciona porque ambas matrices tienen tanto el mismo size como el mismo shape (2,3,5).
# Los elementos están colocados de la misma manera, y por eso se pueden sumar.

[[[1.01042386 1.60222484 1.13863902 1.78242599 1.66747235]
  [1.99408251 1.01330262 1.56930953 1.53004968 1.77131408]
  [1.7795981  1.37212895 1.8361423  1.21523804 1.19163755]]

 [[1.20523398 1.78108949 1.22851268 1.37358585 1.20732939]
  [1.15271141 1.53981642 1.15132512 1.35939217 1.80886519]
  [1.92256238 1.12795171 1.83543513 1.05591957 1.24453589]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [261]:
# your code/answer here

print(a)

[[[0.01042386 0.60222484 0.13863902 0.78242599 0.66747235]
  [0.99408251 0.01330262 0.56930953 0.53004968 0.77131408]
  [0.7795981  0.37212895 0.8361423  0.21523804 0.19163755]]

 [[0.20523398 0.78108949 0.22851268 0.37358585 0.20732939]
  [0.15271141 0.53981642 0.15132512 0.35939217 0.80886519]
  [0.92256238 0.12795171 0.83543513 0.05591957 0.24453589]]]


In [262]:
print(d)

[[[1.01042386 1.60222484 1.13863902 1.78242599 1.66747235]
  [1.99408251 1.01330262 1.56930953 1.53004968 1.77131408]
  [1.7795981  1.37212895 1.8361423  1.21523804 1.19163755]]

 [[1.20523398 1.78108949 1.22851268 1.37358585 1.20732939]
  [1.15271141 1.53981642 1.15132512 1.35939217 1.80886519]
  [1.92256238 1.12795171 1.83543513 1.05591957 1.24453589]]]


In [263]:
# La matrix "d" es igual que la matriz "a" pero sumando 1 a cada elemento.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [264]:
# your code here

e = np.multiply(a, c)

print(e)

[[[0.01042386 0.60222484 0.13863902 0.78242599 0.66747235]
  [0.99408251 0.01330262 0.56930953 0.53004968 0.77131408]
  [0.7795981  0.37212895 0.8361423  0.21523804 0.19163755]]

 [[0.20523398 0.78108949 0.22851268 0.37358585 0.20732939]
  [0.15271141 0.53981642 0.15132512 0.35939217 0.80886519]
  [0.92256238 0.12795171 0.83543513 0.05591957 0.24453589]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [265]:
# your code/answer here

np.array_equal(a,e) 

# Iguales porque estamos multiplicando todos los elementos de la matriz "a" por 1, que son los elementos de la matriz "d"

True

In [266]:
# Otra manera que he encontrado sería (a==e).all() - Comparada que todos los elementos de ambas matrices, sean iguales.

(a==e).all()

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [267]:
# your code here

d_max = np.max(d) # Otra forma d_max = d.max()
print ("The max value in d is:", d_max)

d_min = np.min(d) # Otra forma d_max = d.min()
print ("The min value in d is:", d_min)

d_mean = np.mean(d) # Otra forma d_max = d.mean()
print ("The mean value in d is:", d_mean)

The max value in d is: 1.994082511354315
The min value in d is: 1.0104238597673396
The mean value in d is: 1.4489418598424342


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [275]:
# your code here

f = np.empty([2, 3, 5])


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [276]:
# your code here

# No sé si el objetivo del ejercicio es que lo hiciéramos iterando, pero de esa manera no he sabido como plantearlo.
# He encontrado esta forma en stackoverflow y me funciona.
# Lo interpreto como reemplazar directamente los elementos de la función f por cada valor (según los criterios de d)

f [(d > d_min) & (d < d_mean)] = 25 # d larger than d_min but smaller than d_mean
f [(d > d_mean) & (d < d_max)] = 75 # d larger than d_mean but smaller than d_max
f [(d == d_mean)] = 50 # d equals to d_mean
f [(d == d_min)] = 0 # for d_min in d
f [(d == d_max)] = 100 # for d_max in d


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [277]:
# your code here

print (d)

[[[1.01042386 1.60222484 1.13863902 1.78242599 1.66747235]
  [1.99408251 1.01330262 1.56930953 1.53004968 1.77131408]
  [1.7795981  1.37212895 1.8361423  1.21523804 1.19163755]]

 [[1.20523398 1.78108949 1.22851268 1.37358585 1.20732939]
  [1.15271141 1.53981642 1.15132512 1.35939217 1.80886519]
  [1.92256238 1.12795171 1.83543513 1.05591957 1.24453589]]]


In [278]:
print (f)

[[[  0.  75.  25.  75.  75.]
  [100.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [280]:
# your code here

f_letters = np.empty([2, 3, 5])

f_letters [(f == 0)] = "A"
f_letters [(f == 25)] = "B"
f_letters [(f == 50)] = "C"
f_letters [(f == 75)] = "D"
f_letters [(f == 100)] = "E"

print(f_letters)

# He seguido la misma lógica que en el ejercicio anterior, pero me da error que no sé solucionar.
# ValueError: could not convert string to float: 'A'
# Si hago print(f.dtype) me indica que es float64. No entiendo porque me dice que no puede convertir desde string.


ValueError: could not convert string to float: 'A'